(() => {
  'use strict';

  const departmentStore=window.SavingioV2DepartmentStore;
  if(!departmentStore)throw new Error('Department Store is not loaded');
  if(window.SavingioV2WorkflowEngine)throw new Error('Workflow Engine already exists');

  const STORAGE_KEY='savingio-admin-v2-workflows';
  const FLOW=Object.freeze(['content','seo','image','qa','deploy','analytics','revenue']);
  const TERMINAL=Object.freeze(['done','error']);
  const PRIORITIES=Object.freeze(['urgent','normal']);
  const APPROVAL_STATES=Object.freeze(['none','pending','approved','rejected']);
  const DEPLOY_STATES=Object.freeze(['none','queued','github','cloudflare','verifying','verified','failed','rolled-back']);
  const ANALYTICS_STATES=Object.freeze(['none','queued','collecting','search-console','performance','verified','failed']);
  const REVENUE_STATES=Object.freeze(['none','queued','adsense','affiliate','conversion','settlement','verified','failed']);
  const clone=value=>JSON.parse(JSON.stringify(value));
  const now=()=>new Date().toISOString();
  const makeId=()=>`wf-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;

  function normalizeJob(value={}){
    const stage=FLOW.includes(value.stage)?value.stage:'content';
    const status=['pending','running','done','error'].includes(value.status)?value.status:'pending';
    const type=String(value.type||'new-content');
    const priority=PRIORITIES.includes(value.priority)?value.priority:(type==='urgent-fix'?'urgent':'normal');
    const approvalStatus=APPROVAL_STATES.includes(value.approvalStatus)?value.approvalStatus:'none';
    const deployStatus=DEPLOY_STATES.includes(value.deployStatus)?value.deployStatus:(stage==='deploy'?'queued':'none');
    const analyticsStatus=ANALYTICS_STATES.includes(value.analyticsStatus)?value.analyticsStatus:(stage==='analytics'?'queued':'none');
    const revenueStatus=REVENUE_STATES.includes(value.revenueStatus)?value.revenueStatus:(stage==='revenue'?'queued':'none');
    return {
      id:String(value.id||makeId()),projectId:String(value.projectId||''),title:String(value.title||'제목 없음'),type,priority,
      owner:stage,stage,status,approvalStatus,deployStatus,analyticsStatus,revenueStatus,
      approvalRequestedAt:String(value.approvalRequestedAt||''),approvalResolvedAt:String(value.approvalResolvedAt||''),approvalNote:String(value.approvalNote||''),
      deployUpdatedAt:String(value.deployUpdatedAt||''),deployNote:String(value.deployNote||''),analyticsUpdatedAt:String(value.analyticsUpdatedAt||''),analyticsNote:String(value.analyticsNote||''),
      revenueUpdatedAt:String(value.revenueUpdatedAt||''),revenueNote:String(value.revenueNote||''),
      createdAt:String(value.createdAt||now()),updatedAt:String(value.updatedAt||now()),history:Array.isArray(value.history)?clone(value.history):[]
    };
  }

  function readAll(){let raw=[];try{raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{}return Object.freeze((Array.isArray(raw)?raw:[]).map(normalizeJob));}
  function persist(list){const normalized=list.map(normalizeJob);localStorage.setItem(STORAGE_KEY,JSON.stringify(normalized));syncDepartments(normalized);window.dispatchEvent(new CustomEvent('savingio:v2-workflows-changed',{detail:{count:normalized.length}}));return Object.freeze(normalized.map(item=>Object.freeze(clone(item))));}
  function syncDepartments(list=readAll()){FLOW.forEach(id=>{const jobs=list.filter(job=>job.stage===id&&!TERMINAL.includes(job.status));const hasError=list.some(job=>job.stage===id&&job.status==='error');const hasRunning=jobs.some(job=>job.status==='running');departmentStore.write(id,{status:hasError?'error':hasRunning?'running':jobs.length?'pending':'ready',items:jobs.length,updated:now()});});}
  function create(input={}){const list=clone(readAll());const job=normalizeJob({projectId:input.projectId,title:input.title,type:input.type,priority:input.priority,stage:'content',status:'pending',approvalStatus:'none',deployStatus:'none',analyticsStatus:'none',revenueStatus:'none',history:[{stage:'content',status:'pending',at:now(),note:'워크플로 생성'}]});list.push(job);persist(list);return Object.freeze(clone(job));}
  function update(id,patch={}){const list=clone(readAll());const index=list.findIndex(job=>job.id===id);if(index<0)throw new Error(`Workflow not found: ${id}`);list[index]=normalizeJob({...list[index],...patch,updatedAt:now()});persist(list);return Object.freeze(clone(list[index]));}
  function get(id){const job=readAll().find(item=>item.id===id);if(!job)throw new Error(`Workflow not found: ${id}`);return job;}
  function start(id){const current=get(id);if(TERMINAL.includes(current.status))throw new Error(`Workflow cannot start from ${current.status}`);if(current.approvalStatus==='pending')throw new Error('승인 대기 중인 작업은 시작할 수 없습니다');return update(id,{status:'running',deployStatus:current.stage==='deploy'&&current.deployStatus==='none'?'queued':current.deployStatus,analyticsStatus:current.stage==='analytics'&&current.analyticsStatus==='none'?'queued':current.analyticsStatus,revenueStatus:current.stage==='revenue'&&current.revenueStatus==='none'?'queued':current.revenueStatus,history:[...current.history,{stage:current.stage,status:'running',at:now(),note:'작업 시작'}]});}
  function requestApproval(id,note='QA 완료 · 배포 승인 요청'){const current=get(id);if(current.stage!=='qa'||current.status!=='running')throw new Error('QA 진행 중인 작업만 승인을 요청할 수 있습니다');return update(id,{status:'pending',approvalStatus:'pending',approvalRequestedAt:now(),approvalResolvedAt:'',approvalNote:String(note),history:[...current.history,{stage:'qa',status:'pending',at:now(),note:String(note)}]});}
  function approve(id,note='운영자 승인'){const current=get(id);if(current.approvalStatus!=='pending')throw new Error('승인 대기 중인 작업이 아닙니다');const history=[...current.history,{stage:'qa',status:'done',at:now(),note:String(note)},{stage:'deploy',status:'pending',at:now(),note:'승인 완료 · 배포 부서 전달'}];return update(id,{stage:'deploy',owner:'deploy',status:'pending',approvalStatus:'approved',approvalResolvedAt:now(),approvalNote:String(note),deployStatus:'queued',deployUpdatedAt:now(),deployNote:'배포 대기열 등록',history});}
  function reject(id,note='운영자 반려'){const current=get(id);if(current.approvalStatus!=='pending')throw new Error('승인 대기 중인 작업이 아닙니다');const message=String(note||'운영자 반려');return update(id,{stage:'qa',owner:'qa',status:'error',approvalStatus:'rejected',approvalResolvedAt:now(),approvalNote:message,history:[...current.history,{stage:'qa',status:'error',at:now(),note:message}]});}
  function deployNext(id){const current=get(id);if(current.stage!=='deploy')throw new Error('배포 단계 작업이 아닙니다');const order=['queued','github','cloudflare','verifying','verified'];const index=order.indexOf(current.deployStatus);if(index<0||current.deployStatus==='verified')throw new Error('현재 배포 상태에서는 다음 단계로 이동할 수 없습니다');const next=order[index+1];const labels={github:'GitHub main 반영',cloudflare:'Cloudflare Pages 배포',verifying:'실제 URL 검사',verified:'배포 검증 완료'};const history=[...current.history,{stage:'deploy',status:next==='verified'?'done':'running',at:now(),note:labels[next]}];if(next==='verified'){history.push({stage:'analytics',status:'pending',at:now(),note:'배포 검증 완료 · 분석 부서 전달'});return update(id,{stage:'analytics',owner:'analytics',status:'pending',deployStatus:next,deployUpdatedAt:now(),deployNote:labels[next],analyticsStatus:'queued',analyticsUpdatedAt:now(),analyticsNote:'분석 대기열 등록',history});}return update(id,{status:'running',deployStatus:next,deployUpdatedAt:now(),deployNote:labels[next],history});}
  function deployFail(id,note='배포 오류'){const current=get(id);if(current.stage!=='deploy')throw new Error('배포 단계 작업이 아닙니다');const message=String(note);return update(id,{status:'error',deployStatus:'failed',deployUpdatedAt:now(),deployNote:message,history:[...current.history,{stage:'deploy',status:'error',at:now(),note:message}]});}
  function rollback(id,note='운영자 롤백 기록'){const current=get(id);if(current.deployStatus==='none')throw new Error('배포 기록이 없는 작업입니다');const message=String(note);return update(id,{stage:'deploy',owner:'deploy',status:'error',deployStatus:'rolled-back',deployUpdatedAt:now(),deployNote:message,history:[...current.history,{stage:'deploy',status:'error',at:now(),note:message}]});}
  function analyticsNext(id){const current=get(id);if(current.stage!=='analytics')throw new Error('분석 단계 작업이 아닙니다');const order=['queued','collecting','search-console','performance','verified'];const index=order.indexOf(current.analyticsStatus);if(index<0||current.analyticsStatus==='verified')throw new Error('현재 분석 상태에서는 다음 단계로 이동할 수 없습니다');const next=order[index+1];const labels={collecting:'방문·클릭 데이터 수집','search-console':'Search Console 지표 확인',performance:'콘텐츠 성과 분석',verified:'분석 검증 완료'};const history=[...current.history,{stage:'analytics',status:next==='verified'?'done':'running',at:now(),note:labels[next]}];if(next==='verified'){history.push({stage:'revenue',status:'pending',at:now(),note:'분석 검증 완료 · 수익 부서 전달'});return update(id,{stage:'revenue',owner:'revenue',status:'pending',analyticsStatus:next,analyticsUpdatedAt:now(),analyticsNote:labels[next],revenueStatus:'queued',revenueUpdatedAt:now(),revenueNote:'수익 점검 대기열 등록',history});}return update(id,{status:'running',analyticsStatus:next,analyticsUpdatedAt:now(),analyticsNote:labels[next],history});}
  function analyticsFail(id,note='분석 오류'){const current=get(id);if(current.stage!=='analytics')throw new Error('분석 단계 작업이 아닙니다');const message=String(note);return update(id,{status:'error',analyticsStatus:'failed',analyticsUpdatedAt:now(),analyticsNote:message,history:[...current.history,{stage:'analytics',status:'error',at:now(),note:message}]});}
  function revenueNext(id){const current=get(id);if(current.stage!=='revenue')throw new Error('수익 단계 작업이 아닙니다');const order=['queued','adsense','affiliate','conversion','settlement','verified'];const index=order.indexOf(current.revenueStatus);if(index<0||current.revenueStatus==='verified')throw new Error('현재 수익 상태에서는 다음 단계로 이동할 수 없습니다');const next=order[index+1];const labels={adsense:'AdSense 연결·정책 상태 확인',affiliate:'제휴 링크 상태 확인',conversion:'전환 추적 상태 확인',settlement:'정산 데이터 상태 확인',verified:'수익 점검 완료'};const done=next==='verified';return update(id,{status:done?'done':'running',revenueStatus:next,revenueUpdatedAt:now(),revenueNote:labels[next],history:[...current.history,{stage:'revenue',status:done?'done':'running',at:now(),note:labels[next]}]});}
  function revenueFail(id,note='수익 점검 오류'){const current=get(id);if(current.stage!=='revenue')throw new Error('수익 단계 작업이 아닙니다');const message=String(note);return update(id,{status:'error',revenueStatus:'failed',revenueUpdatedAt:now(),revenueNote:message,history:[...current.history,{stage:'revenue',status:'error',at:now(),note:message}]});}
  function advance(id){const current=get(id);if(current.status!=='running')throw new Error('Only running workflow can advance');if(current.stage==='qa')return requestApproval(id);if(current.stage==='deploy')return deployNext(id);if(current.stage==='analytics')return analyticsNext(id);if(current.stage==='revenue')return revenueNext(id);const index=FLOW.indexOf(current.stage);const history=[...current.history,{stage:current.stage,status:'done',at:now(),note:'단계 완료'}];if(index===FLOW.length-1)return update(id,{status:'done',history});const next=FLOW[index+1];history.push({stage:next,status:'pending',at:now(),note:'다음 부서 전달'});return update(id,{stage:next,owner:next,status:'pending',history});}
  function fail(id,message='오류 발생'){const current=get(id);if(current.stage==='deploy')return deployFail(id,message);if(current.stage==='analytics')return analyticsFail(id,message);if(current.stage==='revenue')return revenueFail(id,message);return update(id,{status:'error',history:[...current.history,{stage:current.stage,status:'error',at:now(),note:String(message)}]});}
  function retry(id){const current=get(id);if(current.status!=='error')throw new Error('Only errored workflow can retry');const deployStatus=current.stage==='deploy'?'queued':current.deployStatus;const analyticsStatus=current.stage==='analytics'?'queued':current.analyticsStatus;const revenueStatus=current.stage==='revenue'?'queued':current.revenueStatus;return update(id,{status:'pending',deployStatus,analyticsStatus,revenueStatus,approvalStatus:current.approvalStatus==='rejected'?'none':current.approvalStatus,history:[...current.history,{stage:current.stage,status:'pending',at:now(),note:'재시도 대기'}]});}
  function stageJobs(stage,{includeDone=false}={}){if(!FLOW.includes(stage))return Object.freeze([]);const jobs=readAll().filter(job=>job.stage===stage&&(includeDone||!TERMINAL.includes(job.status)));jobs.sort((a,b)=>((a.priority==='urgent'?0:1)-(b.priority==='urgent'?0:1))||new Date(a.createdAt)-new Date(b.createdAt));return Object.freeze(jobs.map(job=>Object.freeze(clone(job))));}
  function approvalJobs(status='pending'){const jobs=readAll().filter(job=>status==='all'?job.approvalStatus!=='none':job.approvalStatus===status);jobs.sort((a,b)=>new Date(b.approvalRequestedAt||b.updatedAt)-new Date(a.approvalRequestedAt||a.updatedAt));return Object.freeze(jobs.map(job=>Object.freeze(clone(job))));}
  function deployJobs(status='all'){const jobs=readAll().filter(job=>status==='all'?job.deployStatus!=='none':job.deployStatus===status);jobs.sort((a,b)=>new Date(b.deployUpdatedAt||b.updatedAt)-new Date(a.deployUpdatedAt||a.updatedAt));return Object.freeze(jobs.map(job=>Object.freeze(clone(job))));}
  function analyticsJobs(status='all'){const jobs=readAll().filter(job=>status==='all'?job.analyticsStatus!=='none':job.analyticsStatus===status);jobs.sort((a,b)=>new Date(b.analyticsUpdatedAt||b.updatedAt)-new Date(a.analyticsUpdatedAt||a.updatedAt));return Object.freeze(jobs.map(job=>Object.freeze(clone(job))));}
  function revenueJobs(status='all'){const jobs=readAll().filter(job=>status==='all'?job.revenueStatus!=='none':job.revenueStatus===status);jobs.sort((a,b)=>new Date(b.revenueUpdatedAt||b.updatedAt)-new Date(a.revenueUpdatedAt||a.updatedAt));return Object.freeze(jobs.map(job=>Object.freeze(clone(job))));}
  function summary(){const jobs=readAll();const state=jobs.reduce((acc,job)=>{acc[job.status]=(acc[job.status]||0)+1;return acc},{pending:0,running:0,done:0,error:0});const stages=Object.fromEntries(FLOW.map(stage=>[stage,jobs.filter(job=>job.stage===stage&&!TERMINAL.includes(job.status)).length]));const approvals=jobs.reduce((acc,job)=>{acc[job.approvalStatus]=(acc[job.approvalStatus]||0)+1;return acc},{none:0,pending:0,approved:0,rejected:0});const deployments=jobs.reduce((acc,job)=>{acc[job.deployStatus]=(acc[job.deployStatus]||0)+1;return acc},Object.fromEntries(DEPLOY_STATES.map(key=>[key,0])));const analytics=jobs.reduce((acc,job)=>{acc[job.analyticsStatus]=(acc[job.analyticsStatus]||0)+1;return acc},Object.fromEntries(ANALYTICS_STATES.map(key=>[key,0])));const revenue=jobs.reduce((acc,job)=>{acc[job.revenueStatus]=(acc[job.revenueStatus]||0)+1;return acc},Object.fromEntries(REVENUE_STATES.map(key=>[key,0])));return Object.freeze({total:jobs.length,state:Object.freeze(state),stages:Object.freeze(stages),approvals:Object.freeze(approvals),deployments:Object.freeze(deployments),analytics:Object.freeze(analytics),revenue:Object.freeze(revenue)});}
  function verify(){const jobs=readAll();const invalid=jobs.filter(job=>!FLOW.includes(job.stage)||!['pending','running','done','error'].includes(job.status)||!PRIORITIES.includes(job.priority)||!APPROVAL_STATES.includes(job.approvalStatus)||!DEPLOY_STATES.includes(job.deployStatus)||!ANALYTICS_STATES.includes(job.analyticsStatus)||!REVENUE_STATES.includes(job.revenueStatus));return Object.freeze({storageKey:STORAGE_KEY,flow:FLOW,count:jobs.length,invalid:invalid.length,approvalPending:jobs.filter(job=>job.approvalStatus==='pending').length,deployActive:jobs.filter(job=>job.stage==='deploy'&&!TERMINAL.includes(job.status)).length,analyticsActive:jobs.filter(job=>job.stage==='analytics'&&!TERMINAL.includes(job.status)).length,revenueActive:jobs.filter(job=>job.stage==='revenue'&&!TERMINAL.includes(job.status)).length,pass:invalid.length===0});}

  syncDepartments();
  Object.defineProperty(window,'SavingioV2WorkflowEngine',{value:Object.freeze({create,readAll,stageJobs,approvalJobs,deployJobs,analyticsJobs,revenueJobs,start,advance,requestApproval,approve,reject,deployNext,deployFail,rollback,analyticsNext,analyticsFail,revenueNext,revenueFail,fail,retry,summary,verify,flow:FLOW,priorities:PRIORITIES,approvalStates:APPROVAL_STATES,deployStates:DEPLOY_STATES,analyticsStates:ANALYTICS_STATES,revenueStates:REVENUE_STATES,storageKey:STORAGE_KEY}),writable:false,configurable:false,enumerable:true});
})();