(function(){
 const C=window.SAVINGIO_CALCULATORS||{};
 const $=(s,r=document)=>r.querySelector(s);
 function today(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
 function parseMoney(v){return Number(String(v||'').replace(/[^0-9.-]/g,''))||0}
 function field(f){const cls='sv2-field'+(f.full?' full':'');let input='';
  if(f.type==='select')input=`<select class="sv2-select" id="${f.id}">${f.options.map(o=>`<option value="${o[0]}" ${String(f.value)===String(o[0])?'selected':''}>${o[1]}</option>`).join('')}</select>`;
  else if(f.type==='radio')input=`<div class="sv2-radio-group">${f.options.map(o=>`<label class="sv2-radio"><input type="radio" name="${f.id}" value="${o[0]}" ${String(f.value)===String(o[0])?'checked':''}><span>${o[1]}</span></label>`).join('')}</div>`;
  else {const typ=f.type==='money'?'text':f.type;input=`<input class="sv2-input" id="${f.id}" type="${typ}" ${f.type==='money'?'data-money inputmode="numeric"':''} ${f.today?'data-today':''} ${f.min!==undefined?`min="${f.min}"`:''} ${f.max!==undefined?`max="${f.max}"`:''} ${f.step!==undefined?`step="${f.step}"`:''} ${f.value!==undefined?`value="${f.value}"`:''} ${f.placeholder?`placeholder="${f.placeholder}"`:''}>`;}
  return `<div class="${cls}"><label for="${f.id}">${f.label}</label>${input}${f.help?`<small>${f.help}</small>`:''}</div>`;
 }
 function shell(cfg){document.title=cfg.title+' | Savingio';const md=$('meta[name=description]');if(md)md.content=cfg.description;$('#calc-title').textContent=cfg.title;$('#calc-description').textContent=cfg.description;$('#calc-fields').innerHTML=cfg.fields.map(field).join('');if(cfg.details&&cfg.details.length){$('#calc-details').innerHTML=`<summary>더 정확하게 계산하기</summary><div class="sv2-grid">${cfg.details.map(field).join('')}</div>`}else $('#calc-details').remove();$('#calc-submit').textContent=cfg.button||'계산하기';$('#calc-notice').textContent=cfg.notice||'';if(cfg.official)$('#calc-official').innerHTML=`<a href="${cfg.official[1]}" target="_blank" rel="noopener">${cfg.official[0]} →</a>`;else $('#calc-official').remove();$('#calc-links').innerHTML=(cfg.links||[]).map(x=>`<a class="sv2-link" href="${x[2]}"><strong>${x[0]}</strong><span>${x[1]}</span></a>`).join('');enhance();}
 function enhance(){document.querySelectorAll('[data-today]').forEach(el=>{if(!el.value)el.value=today();const wrap=document.createElement('div');wrap.className='sv2-date-wrap';el.parentNode.insertBefore(wrap,el);wrap.appendChild(el);const b=document.createElement('button');b.type='button';b.className='sv2-today-btn';b.textContent='오늘';b.onclick=()=>el.value=today();wrap.appendChild(b)});document.querySelectorAll('[data-money]').forEach(el=>{const wrap=document.createElement('div');wrap.className='sv2-money-wrap';el.parentNode.insertBefore(wrap,el);wrap.appendChild(el);const u=document.createElement('span');u.className='sv2-money-unit';u.textContent='원';wrap.appendChild(u);const h=document.createElement('small');h.className='sv2-money-hint';wrap.after(h);const fmt=()=>{const n=parseMoney(el.value);el.value=n?n.toLocaleString('ko-KR'):'';h.textContent=n?korean(n):'숫자만 입력해도 자동으로 원 단위가 표시됩니다.'};el.addEventListener('input',fmt);fmt()})}
 function korean(v){let n=Math.floor(Math.abs(v));if(!n)return '';const out=[];for(const [s,l] of [[100000000,'억'],[10000,'만'],[1,'']]){const q=Math.floor(n/s);if(q){out.push(q.toLocaleString('ko-KR')+l);n%=s}}return out.join(' ')+'원'}
 function values(cfg){const out={};[...(cfg.fields||[]),...(cfg.details||[])].forEach(f=>{if(f.type==='radio')out[f.id]=document.querySelector(`[name="${f.id}"]:checked`)?.value||f.value;else{const el=document.getElementById(f.id);out[f.id]=f.type==='money'||f.type==='number'?parseMoney(el?.value):el?.value}});return out}
 function show(r){$('#sv2-main-label').textContent=r.label;$('#sv2-main-value').textContent=r.value;const b=$('#sv2-badge');b.textContent=r.badge||'';b.style.display=r.badge?'inline-block':'none';$('#sv2-breakdown').innerHTML=(r.rows||[]).map(x=>`<div class="sv2-row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#sv2-explain').textContent=r.explain||'';$('#sv2-result').classList.add('show');$('#sv2-result').scrollIntoView({behavior:'smooth',block:'start'})}
 document.addEventListener('DOMContentLoaded',()=>{const id=document.body.dataset.calculator,cfg=C[id];if(!cfg){document.body.innerHTML='<p>계산기 설정을 찾을 수 없습니다.</p>';return}shell(cfg);$('#calc-form').addEventListener('submit',e=>{e.preventDefault();$('#sv2-error').style.display='none';try{show(cfg.calculate(values(cfg)))}catch(err){const box=$('#sv2-error');box.textContent=err.message||'입력값을 확인해 주세요.';box.style.display='block';box.scrollIntoView({behavior:'smooth',block:'center'})}});$('#calc-reset').onclick=()=>{location.reload()};document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName!=='TEXTAREA'&&!e.target.closest('button')){$('#calc-form').requestSubmit()}})});
})();
