(function(){
  const won=v=>Math.round(v).toLocaleString('ko-KR')+'원';
  const num=(v,d=1)=>Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d});
  const days=(a,b)=>Math.floor((b-a)/86400000)+1;
  const row=(label,value)=>[label,value];
  window.SAVINGIO_CALCULATORS={
    salary:{
      title:'급여 실수령액 계산기', description:'세전 월급만 입력하면 예상 실수령액과 공제 내역을 바로 확인합니다.', button:'예상 실수령액 확인하기',
      fields:[{id:'salary',label:'세전 월급',type:'money',placeholder:'예: 3,000,000',help:'급여명세서의 세전 지급액을 입력하세요.'}],
      details:[{id:'taxfree',label:'월 비과세 금액',type:'money',value:'200,000'},{id:'dependents',label:'부양가족 수(본인 포함)',type:'number',min:1,value:1},{id:'children',label:'20세 이하 자녀 수',type:'number',min:0,value:0}],
      notice:'예상 실수령액은 일반 보험료율과 단순 추정 세액을 적용한 참고 금액입니다. 실제 급여명세서와 차이가 날 수 있습니다.', official:['공식기관 기준 확인하기','https://www.nhis.or.kr/nhis/minwon/initCtrbCalcView.do'],
      links:[['퇴직금 계산기','입사일·퇴사일·월급으로 계산','/calculators/severance.html'],['주휴수당 계산기','시급과 근무일만 입력','/calculators/weekly-pay.html'],['3.3%·초과수당','프리랜서 실수령액 확인','/calculators/percentage.html']],
      calculate(v){const gross=v.salary,tf=Math.min(v.taxfree,gross),dep=v.dependents||1,child=v.children;if(gross<100000)throw Error('세전 월급을 입력해 주세요.');const base=Math.max(0,gross-tf),p=Math.min(Math.max(base,410000),6590000)*.045,h=base*.03595,c=h*(.009448/.0719),e=base*.009,taxable=Math.max(0,base-p-h-c-e);let income=taxable>1060000?Math.max(0,(taxable-1060000)*.025-(dep-1)*12500-child*15000):0,local=income*.1,net=gross-p-h-c-e-income-local;return{label:'예상 월 실수령액',value:won(net),badge:'빠른 계산',rows:[row('세전 월급',won(gross)),row('국민연금',won(p)),row('건강보험',won(h)),row('장기요양보험',won(c)),row('고용보험',won(e)),row('소득세·지방소득세',won(income+local)),row('예상 공제 합계',won(gross-net))],explain:'세전 월급에서 비과세 금액을 제외한 보수에 일반적인 근로자 부담 보험료율을 적용했습니다.'}}
    },
    severance:{title:'퇴직금 계산기',description:'입사일·퇴사일·월급만 입력하면 재직기간과 예상 퇴직금을 자동 계산합니다.',button:'예상 퇴직금 확인하기',fields:[{id:'start',label:'입사일',type:'date'},{id:'end',label:'퇴사일',type:'date',today:true,help:'퇴사 전이면 오늘 날짜 그대로 두세요.'},{id:'salary',label:'세전 월급',type:'money',placeholder:'예: 3,000,000',full:true}],notice:'예상 퇴직금은 입력한 급여가 최근 3개월 동안 동일하다고 가정한 참고 금액입니다.',official:['고용노동부 확인하기','https://www.moel.go.kr/'],links:[['급여 실수령액','월급 공제액 확인','/calculators/salary.html'],['연차 계산기','발생 연차 예상','/calculators/annual-leave.html'],['주휴수당','주급·월 환산','/calculators/weekly-pay.html']],calculate(v){if(!v.start||!v.end||v.salary<=0)throw Error('입사일, 퇴사일, 세전 월급을 입력해 주세요.');const a=new Date(v.start),b=new Date(v.end);if(b<a)throw Error('퇴사일은 입사일보다 뒤여야 합니다.');const d=days(a,b),ok=d>=365,avg=v.salary*3/91,sev=ok?avg*30*(d/365):0,y=Math.floor(d/365),m=Math.floor((d%365)/30),recent=new Date(b);recent.setMonth(recent.getMonth()-3);return{label:'예상 퇴직금',value:won(sev),badge:ok?'1년 이상 재직':'1년 미만 재직',rows:[row('총 재직일수',num(d,0)+'일'),row('재직기간',`${y}년 ${m}개월`),row('1년 충족 여부',ok?'충족':'미충족'),row('최근 3개월 기준 기간',recent.toLocaleDateString('ko-KR')+' ~ '+b.toLocaleDateString('ko-KR')),row('예상 1일 평균임금',won(avg))],explain:ok?'입력한 월급과 계속근로기간을 기준으로 예상했습니다.':'일반적으로 계속근로기간이 1년 미만이면 법정 퇴직금 대상이 아닐 수 있습니다.'}}},
    weekly:{title:'주휴수당 계산기',description:'시급·하루 근무시간·주당 근무일만 입력하면 대상 여부와 주휴수당을 계산합니다.',button:'예상 주휴수당 확인하기',fields:[{id:'wage',label:'시급',type:'money',placeholder:'예: 10,320'},{id:'daily',label:'하루 근무시간',type:'number',step:.5,placeholder:'예: 8'},{id:'days',label:'주당 근무일',type:'number',min:1,max:7,value:5}],details:[{id:'perfect',label:'소정근로일 개근',type:'select',value:'yes',options:[['yes','예'],['no','아니요']]}],notice:'실제 지급 여부는 근로계약, 개근 여부와 사업장 상황에 따라 달라질 수 있습니다.',official:['고용노동부 기준 확인하기','https://1350.moel.go.kr/rtmview.do?id=1000059852'],links:[['3.3%·초과수당','일당과 추가근무 계산','/calculators/percentage.html'],['급여 실수령액','월급 공제 확인','/calculators/salary.html'],['퇴직금','재직기간 자동 계산','/calculators/severance.html']],calculate(v){if(v.wage<=0||v.daily<=0||v.days<=0)throw Error('시급, 하루 근무시간, 주당 근무일을 입력해 주세요.');const weekly=v.daily*v.days,ok=weekly>=15&&v.perfect==='yes',paid=ok?Math.min(8,weekly/40*8):0,holiday=v.wage*paid,basic=v.wage*weekly,week=basic+holiday;return{label:'예상 주휴수당(1주)',value:won(holiday),badge:ok?'예상 대상':'조건 미충족',rows:[row('주간 총 근로시간',num(weekly)+'시간'),row('예상 주휴시간',num(paid)+'시간'),row('기본 주급',won(basic)),row('주휴 포함 주급',won(week)),row('월 환산액',won(week*4.345))],explain:ok?'주간 근로시간을 기준으로 비례 주휴시간을 자동 계산했습니다.':'주 15시간 미만 또는 미개근으로 입력되었습니다.'}}},
    percentage:{title:'3.3%·일당·초과수당 계산기',description:'시급·일당·월급과 근무시간만 입력하면 추가수당, 3.3% 공제액과 예상 수령액을 계산합니다.',button:'예상 수령액 확인하기',fields:[{id:'worker',label:'나는 어떤 형태인가요?',type:'radio',value:'unknown',options:[['employee','회사 지시에 따라 정해진 시간에 근무'],['freelancer','독립적으로 일하는 프리랜서'],['unknown','잘 모르겠어요']]},{id:'basis',label:'급여 기준',type:'select',value:'day',options:[['hour','시급'],['day','일당'],['month','월급']]},{id:'amount',label:'금액',type:'money',placeholder:'예: 120,000'},{id:'baseHours',label:'기본 근무시간',type:'number',step:.5,value:8},{id:'extraHours',label:'초과근무시간',type:'number',step:.5,value:0}],details:[{id:'night',label:'야간근무시간',type:'number',step:.5,value:0},{id:'holiday',label:'휴일근무시간',type:'number',step:.5,value:0},{id:'withhold',label:'3.3% 공제',type:'select',value:'yes',options:[['yes','적용'],['no','적용 안 함']]},{id:'contractRate',label:'프리랜서 추가시간 배율',type:'number',step:.1,value:1}],notice:'3.3% 원천징수와 가산수당 적용 여부는 계약 명칭보다 실제 근무 방식과 근로자성에 따라 달라질 수 있습니다.',official:['근로기준법 확인하기','https://www.law.go.kr/lsSc.do?query=%EA%B7%BC%EB%A1%9C%EA%B8%B0%EC%A4%80%EB%B2%95'],links:[['주휴수당','주 15시간 여부 확인','/calculators/weekly-pay.html'],['월급 실수령액','4대보험 공제 확인','/calculators/salary.html'],['퇴직금','재직기간 기준 계산','/calculators/severance.html']],calculate(v){if(v.amount<=0||v.baseHours<=0)throw Error('금액과 기본 근무시간을 입력해 주세요.');let hourly=v.amount,basic=v.amount;if(v.basis==='day')hourly=v.amount/v.baseHours;else if(v.basis==='month'){hourly=v.amount/209;basic=hourly*v.baseHours}else basic=v.amount*v.baseHours;const emp=hourly*v.extraHours*1.5+hourly*v.night*.5+hourly*v.holiday*1.5,free=hourly*(v.extraHours+v.night+v.holiday)*v.contractRate,extra=v.worker==='freelancer'?free:emp,total=basic+extra,deduct=v.withhold==='yes'?total*.033:0,net=total-deduct;return{label:'예상 실수령액',value:won(net),badge:v.worker==='freelancer'?'프리랜서 계약 기준':v.worker==='employee'?'근로자 기준':'근로자 기준 우선',rows:[row('자동 환산 시급',won(hourly)),row('기본 급여',won(basic)),row('초과근무 예상액',won(extra)),row('공제 전 총액',won(total)),row('3.3% 원천징수',won(deduct))],explain:v.worker==='freelancer'?'입력한 계약 배율을 적용했습니다.':'근로자 기준의 일반적인 가산 배율을 적용한 예상치입니다.'}}},
    leave:{title:'연차 계산기',description:'입사일과 기준일만 입력하면 재직기간과 예상 발생 연차를 확인합니다.',button:'예상 연차 확인하기',fields:[{id:'start',label:'입사일',type:'date'},{id:'end',label:'기준일',type:'date',today:true}],details:[{id:'attendance',label:'출근율 80% 이상인가요?',type:'select',value:'yes',options:[['yes','예'],['unknown','잘 모르겠어요'],['no','아니요']]}],notice:'연차 발생일수는 출근율, 회계연도 운영 방식, 휴직·결근과 회사 규정에 따라 달라질 수 있습니다.',official:['고용노동부 확인하기','https://www.moel.go.kr/'],links:[['퇴직금','재직기간 함께 확인','/calculators/severance.html'],['실수령액','월급 공제 확인','/calculators/salary.html'],['주휴수당','주간 수당 확인','/calculators/weekly-pay.html']],calculate(v){if(!v.start||!v.end)throw Error('입사일과 기준일을 입력해 주세요.');const a=new Date(v.start),b=new Date(v.end);if(b<a)throw Error('기준일은 입사일보다 뒤여야 합니다.');const d=days(a,b),years=d/365;let leave=years<1?Math.min(11,Math.floor(d/30)):15+Math.min(10,Math.floor((Math.floor(years)-1)/2));if(v.attendance==='no')leave=0;return{label:'예상 발생 연차',value:num(leave,0)+'일',badge:years>=1?'1년 이상 근속':'1년 미만 근속',rows:[row('총 재직일수',num(d,0)+'일'),row('재직기간',num(years,1)+'년'),row('예상 연차',num(leave,0)+'일')],explain:years<1?'1개월 개근 시 1일씩 발생하는 일반 기준으로 계산했습니다.':'기본 15일과 장기근속 가산을 반영했습니다.'}}},
    loan:{title:'대출 상환 계산기',description:'대출금·금리·기간만 입력하면 월 상환액과 총이자를 계산합니다.',button:'월 상환액 확인하기',fields:[{id:'principal',label:'대출금',type:'money',placeholder:'예: 100,000,000'},{id:'rate',label:'연이율(%)',type:'number',step:.01,placeholder:'예: 4.5'},{id:'years',label:'상환기간(년)',type:'number',min:1,value:10}],details:[{id:'mode',label:'상환방식',type:'select',value:'equal',options:[['equal','원리금균등'],['principal','원금균등'],['interest','만기일시']]}],notice:'실제 납입액은 금리 적용일, 거치기간, 변동금리, 중도상환수수료 등에 따라 달라질 수 있습니다.',official:['금융감독원 확인하기','https://fine.fss.or.kr/'],links:[['3.3%·공제','비율과 실수령 계산','/calculators/percentage.html'],['급여 실수령액','월 가용금액 확인','/calculators/salary.html'],['대출이자 줄이기','상환 전 확인할 점','/articles/loan-refinancing-check.html']],calculate(v){const p=v.principal,r=v.rate/1200,n=v.years*12;if(p<=0||n<=0)throw Error('대출금, 금리, 기간을 입력해 주세요.');let monthly,totalInterest,first,last;if(v.mode==='equal'){monthly=r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;totalInterest=monthly*n-p;first=last=monthly}else if(v.mode==='principal'){const pp=p/n;first=pp+p*r;last=pp+pp*r;totalInterest=r*p*(n+1)/2;monthly=first}else{monthly=p*r;totalInterest=monthly*n;first=monthly;last=p+monthly}return{label:v.mode==='principal'?'첫 달 예상 상환액':'예상 월 상환액',value:won(monthly),badge:v.mode==='equal'?'원리금균등':v.mode==='principal'?'원금균등':'만기일시',rows:[row('대출 원금',won(p)),row('상환 개월',num(n,0)+'개월'),row('총 이자',won(totalInterest)),row('총 상환액',won(p+totalInterest)),row('첫 달 상환액',won(first)),row('마지막 달 상환액',won(last))],explain:'입력한 연이율이 전체 기간 동안 동일하다고 가정했습니다.'}}},
    vat:{title:'부가세 계산기',description:'공급가액 또는 합계금액 하나만 입력하면 공급가액·부가세·합계를 자동 분리합니다.',button:'부가세 확인하기',fields:[{id:'mode',label:'내가 아는 금액',type:'select',value:'supply',options:[['supply','공급가액'],['total','부가세 포함 합계']]},{id:'amount',label:'금액',type:'money',placeholder:'예: 110,000'}],notice:'일반적인 부가가치세 10% 기준이며 면세, 영세율, 간이과세 예외는 반영하지 않습니다.',official:['국세청 확인하기','https://www.nts.go.kr/'],links:[['3.3%·공제 계산','원천징수액 확인','/calculators/percentage.html'],['대출 계산기','월 상환액 확인','/calculators/loan.html'],['급여 실수령액','공제 후 금액 확인','/calculators/salary.html']],calculate(v){if(v.amount<=0)throw Error('금액을 입력해 주세요.');let supply,vat,total;if(v.mode==='supply'){supply=v.amount;vat=v.amount*.1;total=v.amount+vat}else{total=v.amount;supply=v.amount/1.1;vat=total-supply}return{label:'부가세 포함 합계',value:won(total),badge:'일반 10% 기준',rows:[row('공급가액',won(supply)),row('부가세',won(vat)),row('합계금액',won(total))],explain:'알고 있는 금액 하나만 입력하면 나머지는 Savingio가 자동으로 분리합니다.'}}},
    discount:{title:'할인 가격 계산기',description:'원래 가격과 할인율만 입력하면 할인 금액과 최종 결제 금액을 바로 계산합니다.',button:'최종 가격 확인하기',fields:[{id:'price',label:'원래 가격',type:'money',placeholder:'예: 89,000'},{id:'rate',label:'할인율(%)',type:'number',min:0,max:100,step:.1,placeholder:'예: 25'}],details:[{id:'coupon',label:'추가 쿠폰 금액',type:'money',value:'0'},{id:'quantity',label:'수량',type:'number',min:1,value:1}],notice:'실제 결제 금액은 쿠폰 중복 적용, 배송비, 카드 할인과 판매처 정책에 따라 달라질 수 있습니다.',official:null,links:[['퍼센트·공제 계산','비율 계산하기','/calculators/percentage.html'],['대출 계산기','월 상환액 확인','/calculators/loan.html'],['전체 계산기','다른 계산기 찾기','/calculators/']],calculate(v){if(v.price<=0)throw Error('원래 가격을 입력해 주세요.');if(v.rate<0||v.rate>100)throw Error('할인율은 0~100 사이로 입력해 주세요.');const qty=v.quantity||1,original=v.price*qty,discount=original*(v.rate/100),final=Math.max(0,original-discount-v.coupon);return{label:'최종 결제 예상금액',value:won(final),badge:`${num(v.rate,1)}% 할인`,rows:[row('원래 총가격',won(original)),row('할인 금액',won(discount)),row('추가 쿠폰',won(v.coupon)),row('총 절약액',won(original-final))],explain:'원래 가격과 할인율만 입력하면 Savingio가 할인액과 최종 결제액을 계산합니다.'}}}
  };
})();
