(() => {
  'use strict';
  const registry=window.SavingioV2Modules;
  const renderer=window.SavingioV2CenterRenderer;
  const store=window.SavingioV2CloudflareStore;
  if(!registry||!renderer||!store)throw new Error('Cloudflare Center dependencies are not loaded');
  const labels={unknown:'미확인',connected:'연결됨',disconnected:'미연결',error:'오류',pending:'대기',healthy:'정상',warning:'주의',failed:'실패'};
  const stateOptions=store.stateValues.map(value=>({value,label:labels[value]}));
  const config={id:'tool-cloudflare',kicker:'CLOUDFLARE CENTER',title:'Cloudflare Center',description:'Savingio Pages 배포, Production, DNS, SSL, Cache 상태를 실제 확인한 내용만 기록합니다. 외부 API가 연결되지 않은 상태에서는 자동 성공으로 표시하지 않습니다.',formId:'cloudflareForm',formTitle:'Cloudflare 상태 기록',saveLabel:'Cloudflare 상태 저장',resetAction:'cloudflare',metrics:[{label:'계정 연결',value:data=>labels[data.accountStatus]||data.accountStatus},{label:'Pages',value:data=>labels[data.pagesStatus]||data.pagesStatus},{label:'Production',value:data=>labels[data.productionStatus]||data.productionStatus},{label:'DNS',value:data=>labels[data.dnsStatus]||data.dnsStatus},{label:'SSL',value:data=>labels[data.sslStatus]||data.sslStatus},{label:'API',value:data=>data.apiConnected==='true'?'연결됨':'미연결'}],locks:[{label:'Domain',value:store.domain},{label:'Pages project',value:store.project},{label:'허위 배포 성공 방지',value:(data,integrity)=>integrity.noFakeDeploy?'LOCK':'FAIL'}],fields:[{name:'accountStatus',label:'계정 연결 상태',type:'select',options:store.connectionStates.map(value=>({value,label:labels[value]}))},{name:'pagesStatus',label:'Pages 상태',type:'select',options:stateOptions},{name:'productionStatus',label:'Production 상태',type:'select',options:stateOptions},{name:'dnsStatus',label:'DNS 상태',type:'select',options:stateOptions},{name:'sslStatus',label:'SSL 상태',type:'select',options:stateOptions},{name:'cacheStatus',label:'Cache 상태',type:'select',options:stateOptions},{name:'lastDeployId',label:'최근 Deploy ID',maxlength:160,placeholder:'실제 확인한 배포 ID'},{name:'lastDeployAt',label:'최근 배포 시각',maxlength:80,placeholder:'예: 2026-07-26 14:30 KST'},{name:'apiConnected',label:'Cloudflare API 연결',type:'select',options:[{value:'false',label:'미연결'},{value:'true',label:'연결됨'}]},{name:'operatorNote',label:'운영 메모',type:'textarea',rows:5,maxlength:2000,placeholder:'실제 확인한 내용만 입력'}],historyColumns:['productionStatus','sslStatus'],externalTitle:'외부 실행 상태',external:[{label:'Cloudflare API',value:data=>data.apiConnected==='true'?'연결됨':'미연결'},{label:'실제 Deploy 실행',value:'미구현 · 상태 기록만 가능'},{label:'Cache purge 실행',value:'미구현'},{label:'DNS 변경 실행',value:'미구현'},{label:'허위 Production PASS 생성',value:'금지'}]};
  registry.register({id:config.id,title:config.title,render(){return renderer.render(config,store.read(),store.verify())}});
  document.addEventListener('submit',event=>{const form=event.target.closest('#cloudflareForm');if(!form)return;event.preventDefault();store.write(renderer.formData(form,config.fields));});
  document.addEventListener('click',event=>{const button=event.target.closest('[data-center-reset="cloudflare"]');if(!button)return;event.preventDefault();store.reset();});
})();