(() => {
  'use strict';
  const registry=window.SavingioV2Modules;
  const store=window.SavingioV2ProjectStore;
  if(!registry||!store)throw new Error('Admin V2 core is not loaded');
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const metric=(label,value,action='')=>`<article class="metric"${action?` data-route="${esc(action)}" role="button" tabindex="0"`:''}><span>${esc(label)}</span><strong>${esc(value)}</strong>${action?'<small>상세 보기 →</small>':''}</article>`;
  function projectCards(list,showStages=false){
    if(!list.length)return '<div class="panel empty">해당 조건의 프로젝트가 없습니다.</div>';
    return `<div class="project-list">${list.map(project=>`<article class="project-card"><div class="project-top"><div><div class="project-title">${esc(project.title)}</div><div class="meta">${esc(project.id)} · ${esc(project.category)} · ${esc(project.type)}</div></div><span class="status ${esc(project.status)}">${esc(project.statusLabel)}</span></div><div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(project.progress||0)))}%"></i></div><div class="meta">진행률 ${Number(project.progress||0)}% · ${esc(project.updated||'')}</div>${showStages?`<div class="stage-list">${(project.stages||[]).map(([name,state])=>`<div class="stage ${esc(state)}"><span>${state==='done'?'✓':state==='active'?'●':'·'}</span><strong>${esc(name)}</strong><small>${state==='done'?'완료':state==='active'?'진행 중':'대기'}</small></div>`).join('')}</div>`:''}</article>`).join('')}</div>`;
  }
  const view=(eyebrow,title,description,body)=>`<section class="view" data-module-root><header class="hero"><p>${esc(eyebrow)}</p><h2>${esc(title)}</h2><p>${esc(description)}</p></header>${body}</section>`;
  registry.register({id:'command-home',title:'통합 상황실',render(){const list=store.read(),s=store.summary(list);return view('COMMAND CENTER','통합 상황실','전체 운영 현황을 요약하고 각 상세 화면으로 연결합니다.',`<div class="metrics">${metric('전체 진행률',`${s.average}%`,'command-progress')}${metric('진행 중',`${s.state.running}건`,'command-today')}${metric('승인 대기',`${s.state.approval}건`,'command-approval')}${metric('오류·중지',`${s.state.error}건`,'command-error')}${metric('완료',`${s.state.done}건`,'command-progress')}${metric('등록 프로젝트',`${s.total}건`,'command-progress')}</div><div class="two-col"><section class="panel"><h3>진행 중인 프로젝트</h3>${projectCards(list.filter(item=>item.status!=='done'))}</section><aside class="panel"><h3>오늘 확인 순서</h3><ol class="action-list"><li>오류·중지 프로젝트 확인</li><li>승인 대기 프로젝트 검토</li><li>진행 중 활성 단계 확인</li><li>완료 프로젝트 배포 상태 확인</li></ol></aside></div>`);}});
  registry.register({id:'command-progress',title:'전체 진행률',render(){const list=store.read(),s=store.summary(list);return view('COMMAND CENTER','전체 진행률','프로젝트 전체의 진행률과 단계별 상태를 확인합니다.',`<div class="metrics">${metric('평균 진행률',`${s.average}%`)}${metric('진행 중',`${s.state.running}건`)}${metric('승인 대기',`${s.state.approval}건`)}${metric('오류',`${s.state.error}건`)}${metric('완료',`${s.state.done}건`)}${metric('전체',`${s.total}건`)}</div><section class="panel"><h3>프로젝트별 진행 단계</h3>${projectCards(list,true)}</section>`);}});
  registry.register({id:'command-today',title:'오늘 작업',render(){const list=store.read().filter(item=>item.status==='running');return view('COMMAND CENTER','오늘 작업','현재 실행 중인 프로젝트와 활성 단계를 표시합니다.',`<section class="panel"><h3>진행 중 작업</h3>${projectCards(list,true)}</section>`);}});
  registry.register({id:'command-approval',title:'승인 필요',render(){const list=store.read().filter(item=>item.status==='approval');return view('COMMAND CENTER','승인 필요','승인 대기 상태의 프로젝트만 표시합니다.',`<section class="panel"><h3>승인 대기 목록</h3>${projectCards(list,true)}</section>`);}});
  registry.register({id:'command-error',title:'오류·중지',render(){const list=store.read().filter(item=>item.status==='error');return view('COMMAND CENTER','오류·중지','오류 또는 사용자 중지 상태의 프로젝트를 확인합니다.',`<section class="panel"><h3>오류·중지 목록</h3>${projectCards(list,true)}</section>`);}});
  registry.register({id:'command-revenue',title:'수익 요약',render(){const list=store.read(),s=store.summary(list);return view('COMMAND CENTER','수익 요약','확인 가능한 운영 지표만 표시합니다. 실제 수익 데이터는 별도 연결 전까지 만들지 않습니다.',`<div class="metrics">${metric('완료 프로젝트',`${s.state.done}건`)}${metric('진행 중',`${s.state.running}건`)}${metric('승인 대기',`${s.state.approval}건`)}${metric('오류',`${s.state.error}건`)}${metric('평균 진행률',`${s.average}%`)}${metric('수익 데이터','미연결')}</div><section class="panel"><h3>데이터 연결 상태</h3><div class="connection-list"><div><span>상품 DB</span><strong>미연결</strong></div><div><span>제휴 링크</span><strong>미연결</strong></div><div><span>클릭·전환</span><strong>미연결</strong></div><div><span>정산</span><strong>미연결</strong></div></div></section>`);}});
})();