(() => {
  'use strict';
  const registry=window.SavingioV2Modules;
  const store=window.SavingioV2ProjectStore;
  const workflow=window.SavingioV2WorkflowEngine;
  const pipeline=window.SavingioV2PipelineEngine;
  const dashboard=window.SavingioV2OperationsDashboardStore;
  if(!registry||!store||!workflow||!pipeline||!dashboard)throw new Error('Admin V2 Command Center dependencies are not loaded');
  if(window.SavingioV2CommandCenter)throw new Error('Admin V2 Command Center already exists');
  const MODULE_NAME='command-center';
  const MODULE_IDS=Object.freeze(['command-home','command-progress','command-today','command-approval','command-error','command-revenue']);
  const STAGE_LABELS=Object.freeze({content:'콘텐츠',seo:'SEO',image:'이미지',qa:'QA',deploy:'배포',analytics:'분석',revenue:'수익'});
  const STATUS_LABELS=Object.freeze({pending:'대기',running:'진행 중',done:'완료',error:'오류'});
  const APPROVAL_LABELS=Object.freeze({none:'미요청',pending:'승인 대기',approved:'승인',rejected:'반려'});
  const TYPE_LABELS=Object.freeze({'new-content':'새 콘텐츠','content-update':'기존 콘텐츠 수정','seo-recheck':'SEO 재검사','urgent-fix':'긴급 수정'});
  const EXTERNAL_LABELS=Object.freeze({'search-console':'Search Console',analytics:'Google Analytics',adsense:'Google AdSense'});
  const CENTER_MAP=Object.freeze([
    {group:'통합 상황실',id:'command-progress',label:'전체 진행률',description:'전체 워크플로 진행 상태'},
    {group:'통합 상황실',id:'command-today',label:'오늘 작업',description:'현재 처리할 작업'},
    {group:'통합 상황실',id:'command-approval',label:'승인 센터',description:'승인 대기와 배포 전달'},
    {group:'통합 상황실',id:'command-error',label:'오류·중지',description:'실패와 중지 항목 처리'},
    {group:'통합 상황실',id:'command-revenue',label:'수익 요약',description:'추정·확정·정산 수익'},
    {group:'운영 부서',id:'dept-cms',label:'CMS',description:'저장·승인·발행 준비'},
    {group:'운영 부서',id:'dept-content',label:'콘텐츠 인벤토리',description:'콘텐츠 현황 관리'},
    {group:'운영 부서',id:'dept-seo',label:'SEO 운영 센터',description:'SEO 검사와 운영'},
    {group:'운영 부서',id:'dept-image',label:'이미지 인벤토리',description:'이미지 자산 관리'},
    {group:'운영 부서',id:'dept-qa',label:'QA 검수 센터',description:'품질 검수 결과'},
    {group:'운영 부서',id:'dept-deploy',label:'배포 승인 센터',description:'배포 상태와 승인'},
    {group:'운영 부서',id:'dept-analytics',label:'성과 분석 센터',description:'성과와 데이터 신호'},
    {group:'운영 부서',id:'dept-revenue',label:'수익 센터',description:'수익 기록과 정산'},
    {group:'진단 도구',id:'tool-navigation-audit',label:'메뉴·화면 연결 검사',description:'왼쪽 메뉴 전수 검사'},
    {group:'진단 도구',id:'tool-runtime-audit',label:'런타임 검증 센터',description:'모듈과 엔진 실행 검사'},
    {group:'진단 도구',id:'tool-production-verification',label:'운영 검증 센터',description:'운영 자산 최종 검사'},
    {group:'진단 도구',id:'tool-build-progress',label:'개발 진행 보드',description:'구현·검증 진행률'},
    {group:'진단 도구',id:'tool-seo-doctor',label:'SEO Doctor',description:'SEO 문제 진단'},
    {group:'진단 도구',id:'tool-content-doctor',label:'Content Doctor',description:'콘텐츠 품질 진단'},
    {group:'외부 점검',id:'tool-external-connections',label:'외부 데이터 연결',description:'Provider 연결 상태'},
    {group:'외부 점검',id:'tool-search-console',label:'Search Console',description:'색인과 URL 검사'},
    {group:'외부 점검',id:'tool-adsense',label:'AdSense',description:'광고 승인과 운영 상태'},
    {group:'외부 점검',id:'tool-github-release',label:'GitHub Release',description:'릴리스와 커밋 상태'},
    {group:'외부 점검',id:'tool-cloudflare',label:'Cloudflare',description:'배포와 도메인 상태'}
  ]);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const metric=(label,value,action='')=>`<article class="metric"${action?` data-route="${esc(action)}" role="button" tabindex="0"`:''}><span>${esc(label)}</span><strong>${esc(value)}</strong>${action?'<small>상세 보기 →</small>':''}</article>`;
  const time=value=>{const date=new Date(value);return Number.isNaN(date.getTime())?String(value||''):date.toLocaleString('ko-KR');};
  const money=value=>`${Math.round(Number(value)||0).toLocaleString('ko-KR')}원`;
  const view=(eyebrow,title,description,body)=>`<section class="view" data-module-root data-module="${MODULE_NAME}"><header class="hero"><p>${esc(eyebrow)}</p><h2>${esc(title)}</h2><p>${esc(description)}</p></header>${body}</section>`;
  function workflowButtons(job){const oneClick=job.status!=='done'&&job.status!=='error'?`<button class="button secondary" type="button" data-workflow-action="one-click" data-workflow-id="${esc(job.id)}">원클릭 진행</button>`:'';if(job.approvalStatus==='pending')return `${oneClick}<span class="status pending">승인 대기</span>`;if(job.status==='pending')return `<button class="button" type="button" data-workflow-action="start" data-workflow-id="${esc(job.id)}">작업 시작</button>${oneClick}`;if(job.status==='running')return `<button class="button" type="button" data-workflow-action="advance" data-workflow-id="${esc(job.id)}">현재 단계 완료</button>${oneClick}<button class="button secondary" type="button" data-workflow-action="fail" data-workflow-id="${esc(job.id)}">오류 처리</button>`;if(job.status==='error')return `<button class="button" type="button" data-workflow-action="retry" data-workflow-id="${esc(job.id)}">재시도</button>`;return '<span class="status done">완료</span>';}
  function workflowCards(list){if(!list.length)return '<div class="panel empty">등록된 워크플로가 없습니다.</div>';return `<div class="project-list">${list.map(job=>{const index=workflow.flow.indexOf(job.stage);const progress=job.status==='done'?100:Math.round((index+(job.status==='running'?0.5:0))/workflow.flow.length*100);const gate=pipeline.gate(job);return `<article class="project-card"><div class="project-top"><div><div class="project-title">${esc(job.title)}</div><div class="meta">${esc(job.projectId||job.id)} · ${esc(TYPE_LABELS[job.type]||job.type)} · 현재 부서 ${esc(STAGE_LABELS[job.stage])}</div></div><span class="status ${esc(job.status)}">${job.priority==='urgent'?'긴급 · ':''}${esc(STATUS_LABELS[job.status])}</span></div><div class="progress"><i style="width:${progress}%"></i></div><div class="meta">전체 진행률 ${progress}% · ${esc(job.updatedAt)} · 원클릭 게이트: ${esc(gate.label)}</div><div class="header-actions">${workflowButtons(job)}</div></article>`;}).join('')}</div>`;}
  function approvalCards(list){if(!list.length)return '<div class="panel empty">승인 대기 중인 작업이 없습니다.</div>';return `<div class="project-list">${list.map(job=>`<article class="project-card"><div class="project-top"><div><div class="project-title">${esc(job.title)}</div><div class="meta">${esc(job.projectId||job.id)} · ${esc(TYPE_LABELS[job.type]||job.type)} · QA 검수 완료</div></div><span class="status pending">${job.priority==='urgent'?'긴급 · ':''}${esc(APPROVAL_LABELS[job.approvalStatus])}</span></div><div class="meta">요청 ${esc(time(job.approvalRequestedAt))}</div><div class="header-actions"><button class="button" type="button" data-workflow-action="approve" data-workflow-id="${esc(job.id)}">승인 후 배포 전달</button><button class="button secondary" type="button" data-workflow-action="reject" data-workflow-id="${esc(job.id)}">반려</button></div></article>`).join('')}</div>`;}
  function externalIssues(){const adapter=window.SavingioV2ExternalApiAdapter;if(!adapter?.readAll)return [];return adapter.readAll().filter(row=>row.state==='error').map(row=>({kind:'external',item:{id:row.id,title:`${EXTERNAL_LABELS[row.id]||row.id} 동기화 오류`,url:row.id,note:row.error||row.note||'외부 Provider 동기화 실패',route:'tool-external-connections',lastErrorAt:row.lastErrorAt}}));}
  function inventoryIssues(){const sources=[['qa',window.SavingioV2QaInventoryStore],['deploy',window.SavingioV2DeployInventoryStore],['analytics',window.SavingioV2AnalyticsInventoryStore],['revenue',window.SavingioV2RevenueInventoryStore]];const inventory=sources.flatMap(([kind,api])=>(api?.readAll?.()||[]).filter(item=>kind==='qa'?['fail','blocked'].includes(item.result):kind==='deploy'?['failed','rolled-back'].includes(item.status):item.status==='blocked').map(item=>({kind,item})));return [...inventory,...externalIssues()];}
  function issueCards(list){if(!list.length)return '<div class="empty">현재 운영 센터 실패·중지 항목이 없습니다.</div>';return `<div class="project-list">${list.map(({kind,item})=>{const route=kind==='external'?'tool-external-connections':`dept-${kind}`;return `<article class="project-card"><div class="project-top"><div><div class="project-title">${esc(item.title)}</div><div class="meta">${esc(kind.toUpperCase())} · ${esc(item.url||item.targetUrl||item.id)}</div>${item.note?`<div class="meta">${esc(item.note)}</div>`:''}${item.lastErrorAt?`<div class="meta">최근 오류 ${esc(time(item.lastErrorAt))}</div>`:''}</div><span class="status error">문제 확인</span></div><div class="header-actions"><button class="button" type="button" data-operational-action="create-fix" data-operational-kind="${esc(kind)}" data-operational-id="${esc(item.id)}">긴급 수정 생성</button><button class="button secondary" type="button" data-route="${esc(route)}">원본 센터 열기</button></div></article>`;}).join('')}</div>`;}
  function integratedDashboard(){const d=dashboard.read();const external=externalIssues();const active=d.alerts.filter(item=>item.count>0);const alerts=[...active,...(external.length?[{label:'외부 API 동기화 오류',count:external.length,route:'command-error'}]:[])];const html=alerts.length?`<div class="connection-list">${alerts.map(item=>`<div data-route="${esc(item.route)}" role="button" tabindex="0"><span>${esc(item.label)}</span><strong class="fail">${item.count}건</strong></div>`).join('')}</div>`:'<div class="empty">현재 통합 경고가 없습니다.</div>';return `<section class="panel"><h3>부서 통합 현황</h3><div class="metrics">${metric('콘텐츠',`${d.content.total||0}건`,'dept-content')}${metric('SEO',`${d.seo.total||0}건`,'dept-seo')}${metric('이미지',`${d.image.total||0}건`,'dept-image')}${metric('QA PASS',`${d.qa.result?.pass||0}건`,'dept-qa')}${metric('배포 검증',`${d.deploy.verified||0}건`,'dept-deploy')}${metric('분석 검증',`${d.analytics.verified||0}건`,'dept-analytics')}${metric('외부 API 오류',`${external.length}건`,'command-error')}${metric('확정 수익',money(d.revenue.confirmed||0),'dept-revenue')}</div></section><section class="panel"><h3>주의·승인·오류</h3>${html}</section>`;}
  function centerMap(){const groups=[...new Set(CENTER_MAP.map(item=>item.group))];const connected=CENTER_MAP.filter(item=>registry.has(item.id)).length;return `<section class="panel"><div class="project-top"><div><h3>운영 센터 바로가기</h3><div class="meta">왼쪽 검색트리와 동일한 화면을 메인에서 바로 엽니다.</div></div><span class="status ${connected===CENTER_MAP.length?'done':'error'}">${connected}/${CENTER_MAP.length} 연결</span></div>${groups.map(group=>`<div class="center-map-group"><h4>${esc(group)}</h4><div class="center-map-grid">${CENTER_MAP.filter(item=>item.group===group).map(item=>{const ok=registry.has(item.id);return `<button class="center-map-card ${ok?'connected':'disconnected'}" type="button" ${ok?`data-route="${esc(item.id)}"`:`data-broken-route="${esc(item.id)}"`}><span>${esc(item.label)}</span><small>${esc(item.description)}</small><strong>${ok?'화면 열기 →':'연결 끊김'}</strong></button>`;}).join('')}</div></div>`).join('')}<div class="header-actions"><button class="button secondary" type="button" data-route="tool-navigation-audit">전체 메뉴 연결 검사</button></div></section>`;}
  const creationPanel=()=>`<section class="panel"><h3>새 운영 작업 생성</h3><form id="workflowCreateForm"><div class="connection-list"><label><span>작업 제목</span><input name="title" required maxlength="120"></label><label><span>프로젝트 ID 또는 URL</span><input name="projectId" maxlength="160"></label><label><span>작업 유형</span><select name="type"><option value="new-content">새 콘텐츠</option><option value="content-update">기존 콘텐츠 수정</option><option value="seo-recheck">SEO 재검사</option><option value="urgent-fix">긴급 수정</option></select></label></div><div class="header-actions"><button class="button" type="submit">워크플로 생성</button><button class="button secondary" type="button" data-pipeline-action="run-all">전체 원클릭 진행</button></div></form></section>`;
  const pipelinePanel=()=>{const s=pipeline.summary();return `<section class="panel"><h3>One-Click Pipeline</h3><div class="metrics">${metric('자동 진행 가능',`${s.autoReady}건`)}${metric('승인 대기',`${s.approval}건`)}${metric('배포 검증',`${s.deploy}건`)}${metric('분석 확인',`${s.analytics}건`)}${metric('수익 확인',`${s.revenue}건`)}${metric('완료',`${s.done}건`)}</div></section>`;};
  const modules=[
    {id:'command-home',title:'통합 상황실',render(){const wf=workflow.readAll();return view('COMMAND CENTER','통합 상황실','각 운영 센터와 워크플로 상태를 한 화면에서 관리합니다.',`${centerMap()}${integratedDashboard()}${creationPanel()}${pipelinePanel()}<section class="panel"><h3>운영 파이프라인</h3>${workflowCards(wf.filter(x=>x.status!=='done'))}</section>`);}},
    {id:'command-progress',title:'전체 진행률',render(){return view('COMMAND CENTER','전체 진행률','운영 워크플로 전체 진행 상태입니다.',`${integratedDashboard()}${pipelinePanel()}<section class="panel"><h3>워크플로 진행 단계</h3>${workflowCards(workflow.readAll())}</section>`);}},
    {id:'command-today',title:'오늘 작업',render(){const list=workflow.readAll().filter(x=>(x.status==='running'||x.status==='pending')&&x.approvalStatus!=='pending');return view('COMMAND CENTER','오늘 작업','현재 실행 중이거나 다음 행동을 기다리는 작업입니다.',`<section class="panel"><h3>오늘 처리할 워크플로</h3>${workflowCards(list)}</section>`);}},
    {id:'command-approval',title:'승인 센터',render(){const pending=workflow.approvalJobs('pending');const issues=inventoryIssues();const deployReady=(window.SavingioV2DeployInventoryStore?.readAll?.()||[]).filter(x=>x.status==='approved');const s=workflow.summary();return view('APPROVAL CENTER','승인 센터','워크플로 승인과 배포 승인 준비 상태를 통합 확인합니다.',`<div class="metrics">${metric('워크플로 승인 대기',`${s.approvals.pending}건`)}${metric('승인 완료',`${s.approvals.approved}건`)}${metric('반려',`${s.approvals.rejected}건`)}${metric('배포 승인 완료',`${deployReady.length}건`,'dept-deploy')}${metric('운영 문제',`${issues.length}건`,'command-error')}</div><section class="panel"><h3>승인 대기 워크플로</h3>${approvalCards(pending)}</section>`);}},
    {id:'command-error',title:'오류·중지',render(){const wf=workflow.readAll().filter(x=>x.status==='error');const issues=inventoryIssues();const external=externalIssues();return view('COMMAND CENTER','오류·중지','워크플로 오류와 운영 센터·외부 API 실패 항목을 한 곳에서 처리합니다.',`<div class="metrics">${metric('워크플로 오류',`${wf.length}건`)}${metric('운영 센터 문제',`${issues.length-external.length}건`)}${metric('외부 API 오류',`${external.length}건`)}${metric('전체 처리 대상',`${wf.length+issues.length}건`)}</div><section class="panel"><h3>운영 센터·외부 API 실패</h3>${issueCards(issues)}</section><section class="panel"><h3>오류 워크플로</h3>${workflowCards(wf)}</section>`);}},
    {id:'command-revenue',title:'수익 요약',render(){const d=dashboard.read();return view('COMMAND CENTER','수익 요약','추정·확정·정산 수익을 분리합니다.',`<div class="metrics">${metric('수익 기록',`${d.revenue.total||0}건`,'dept-revenue')}${metric('추정 수익',money(d.revenue.estimated||0),'dept-revenue')}${metric('확정 수익',money(d.revenue.confirmed||0),'dept-revenue')}${metric('정산 완료',money(d.revenue.settled||0),'dept-revenue')}${metric('분석 수익 신호',money(d.analytics.revenueSignal||0),'dept-analytics')}</div>`);}}
  ];
  modules.forEach(module=>registry.register(module));
  function handleAction(action,id){if(!['start','advance','fail','retry','approve','reject','one-click'].includes(action))return false;if(action==='start')workflow.start(id);if(action==='advance')workflow.advance(id);if(action==='fail')workflow.fail(id,'운영자 수동 오류 처리');if(action==='retry')workflow.retry(id);if(action==='approve')workflow.approve(id,'Approval Center 운영자 승인');if(action==='reject')workflow.reject(id,'Approval Center 운영자 반려');if(action==='one-click'){const result=pipeline.run(id);alert(`One-Click Pipeline\n\n자동 전환 ${result.transitions.length}단계\n현재 위치: ${STAGE_LABELS[result.job.stage]}\n중지 사유: ${result.gate.label}`);}return true;}
  function handlePipelineAction(action){if(action!=='run-all')return false;const results=pipeline.runAll();alert(`전체 One-Click Pipeline\n\n대상 ${results.length}건`);return true;}
  function handleCreate(form){const data=new FormData(form);const type=String(data.get('type')||'new-content');return workflow.create({title:String(data.get('title')||'').trim(),projectId:String(data.get('projectId')||'').trim(),type,priority:type==='urgent-fix'?'urgent':'normal'});}
  function handleOperationalAction(action,kind,id){if(action!=='create-fix')return false;if(kind==='external'){const row=window.SavingioV2ExternalApiAdapter?.read?.(id);if(!row||row.state!=='error')throw new Error('외부 Provider 오류 원본을 찾을 수 없습니다.');return workflow.create({title:`[긴급] ${EXTERNAL_LABELS[id]||id} 외부 동기화 오류 수정`,projectId:`external:${id}:${row.error||row.note||'sync-error'}`,type:'urgent-fix',priority:'urgent'});}const maps={qa:window.SavingioV2QaInventoryStore,deploy:window.SavingioV2DeployInventoryStore,analytics:window.SavingioV2AnalyticsInventoryStore,revenue:window.SavingioV2RevenueInventoryStore};const item=maps[kind]?.get?.(id);if(!item)throw new Error('운영 문제 원본을 찾을 수 없습니다.');const projectId=item.url||item.targetUrl||item.id;return workflow.create({title:`[긴급] ${item.title} · ${kind.toUpperCase()} 문제 수정`,projectId,type:'urgent-fix',priority:'urgent'});}
  function verify(){const registered=MODULE_IDS.filter(id=>registry.has(id));const a=store.verify(),b=workflow.verify(),c=pipeline.verify(),d=dashboard.verify();const external=externalIssues();const centers=CENTER_MAP.filter(item=>registry.has(item.id));return Object.freeze({name:MODULE_NAME,expected:MODULE_IDS.length,registered:registered.length,ids:Object.freeze(registered),store:a,workflow:b,pipeline:c,dashboard:d,externalIssues:external.length,externalIntegration:Boolean(window.SavingioV2ExternalApiAdapter?.readAll),centerMap:{expected:CENTER_MAP.length,connected:centers.length,missing:CENTER_MAP.filter(item=>!registry.has(item.id)).map(item=>item.id)},pass:registered.length===MODULE_IDS.length&&a.pass&&b.pass&&c.pass&&d.pass&&centers.length===CENTER_MAP.length});}
  Object.defineProperty(window,'SavingioV2CommandCenter',{value:Object.freeze({name:MODULE_NAME,ids:MODULE_IDS,centerMap:CENTER_MAP,verify,handleAction,handlePipelineAction,handleCreate,handleOperationalAction,externalIssues}),writable:false,configurable:false,enumerable:true});
})();