(() => {
  'use strict';
  const registry=window.SavingioV2Modules;
  const renderer=window.SavingioV2CenterRenderer;
  const factory=window.SavingioV2CenterStoreFactory;
  if(!registry||!renderer||!factory)throw new Error('Content Doctor dependencies are not loaded');

  const states={scan:['unknown','pending','running','pass','fail'],length:['unknown','healthy','short','critical'],structure:['unknown','healthy','warning','error'],images:['unknown','healthy','missing','error'],links:['unknown','healthy','warning','broken']};
  const labels={unknown:'미확인',pending:'대기',running:'검사 중',pass:'정상',fail:'실패',healthy:'정상',short:'분량 부족',critical:'심각',warning:'주의',error:'오류',missing:'누락',broken:'깨진 링크'};
  const store=factory.create({key:'savingio-admin-v2-content-doctor',name:'content-doctor',states,defaults:{scan:'unknown',length:'unknown',structure:'unknown',images:'unknown',links:'unknown',lastScanAt:'',checkedArticles:'',issueCount:'',operatorNote:'',history:[]},stateFields:['scan','length','structure','images','links'],historyFields:['scan','length','structure','images','links'],verify(data){const fake=data.scan==='pass'&&(!data.lastScanAt||!data.checkedArticles);return {pass:!fake,noFakeSuccess:!fake};}});
  const options=values=>values.map(value=>({value,label:labels[value]||value}));
  const config={id:'tool-content-doctor',kicker:'CONTENT DOCTOR',title:'Content Doctor',description:'본문 분량·공통 DNA·대표 이미지·내부 링크를 실제 검사한 결과만 기록합니다.',formId:'contentDoctorForm',formTitle:'콘텐츠 검사 상태',saveLabel:'콘텐츠 상태 저장',resetAction:'content-doctor',metrics:[{label:'전체 검사',value:data=>labels[data.scan]||data.scan},{label:'본문 분량',value:data=>labels[data.length]||data.length},{label:'글 구조',value:data=>labels[data.structure]||data.structure},{label:'대표 이미지',value:data=>labels[data.images]||data.images},{label:'내부 링크',value:data=>labels[data.links]||data.links},{label:'진실성 LOCK',value:(data,integrity)=>integrity.noFakeSuccess?'PASS':'FAIL'}],locks:[{label:'PASS 조건',value:'검사 시각과 검사 글 목록이 있어야 PASS 허용'},{label:'CSS 카드의 이미지 인정',value:'금지 · 실제 img/파일만 인정'},{label:'분량 반복 채우기',value:'금지'},{label:'기존 본문 덧씌우기',value:'금지 · URL/H1 보존 후 새 본문 작성'}],fields:[{name:'scan',label:'전체 검사 상태',type:'select',options:options(states.scan)},{name:'length',label:'본문 분량 상태',type:'select',options:options(states.length)},{name:'structure',label:'공통 DNA 상태',type:'select',options:options(states.structure)},{name:'images',label:'대표 이미지 상태',type:'select',options:options(states.images)},{name:'links',label:'내부 링크 상태',type:'select',options:options(states.links)},{name:'lastScanAt',label:'최근 검사 시각',maxlength:80,placeholder:'실제 검사한 시각'},{name:'issueCount',label:'발견 문제 수',type:'number'},{name:'checkedArticles',label:'검사한 글·범위',type:'textarea',rows:7,maxlength:5000},{name:'operatorNote',label:'운영 메모',type:'textarea',rows:4,maxlength:2000}],historyColumns:['scan','length','structure','images','links'],externalTitle:'검사 계약',external:[{label:'본문 최소 기준',value:'Savingio 글쓰기 헌법 적용'},{label:'실제 이미지 확인',value:'img + 파일 + alt + OG'},{label:'Production 확인 전 완료',value:'금지'},{label:'자동 전체 수정',value:'미구현'}]};
  registry.register({id:config.id,title:config.title,render(){return renderer.render(config,store.read(),store.verify())}});
  document.addEventListener('submit',event=>{const form=event.target.closest('#contentDoctorForm');if(!form)return;event.preventDefault();store.write(renderer.formData(form,config.fields));});
  document.addEventListener('click',event=>{const button=event.target.closest('[data-center-reset="content-doctor"]');if(!button)return;event.preventDefault();store.reset();});
})();