(() => {
  'use strict';
  const registry=window.SavingioV2Modules;
  if(!registry)throw new Error('Runtime Audit dependency is not loaded');
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const expectedReleaseId='admin-v2-release-2026-07-26-01';
  const expectedModules=Object.freeze(['tool-build-progress','tool-runtime-audit','tool-production-verification','tool-external-connections','tool-cloudflare','tool-seo-doctor','tool-content-doctor','tool-search-console','tool-adsense','tool-github-release','dept-content','dept-seo','dept-image','dept-qa','dept-deploy','dept-analytics','dept-revenue']);
  const expectedGlobals=Object.freeze(['SavingioV2ReleaseMarker','SavingioV2CenterRenderer','SavingioV2CenterStoreFactory','SavingioV2BuildProgressStore','SavingioV2CloudflareStore','SavingioV2SeoDoctorStore','SavingioV2ContentDoctorStore','SavingioV2ContentInventoryStore','SavingioV2SeoInventoryStore','SavingioV2ImageInventoryStore','SavingioV2QaInventoryStore','SavingioV2DeployInventoryStore','SavingioV2AnalyticsInventoryStore','SavingioV2RevenueInventoryStore','SavingioV2OperationsDashboardStore','SavingioV2ExternalApiAdapter','SavingioV2SearchConsoleProvider','SavingioV2AnalyticsProvider','SavingioV2AdSenseProvider','SavingioV2ExternalRetryEngine','SavingioV2ExternalConnectionsCenter','SavingioV2ProductionVerificationCenter','SavingioV2OperationalActions','SavingioV2ProductionE2EVerify','SavingioV2ProductionDeploymentProbe','SavingioV2RuntimeAudit','SavingioAdminV2','SavingioV2ProductionAutoVerify']);
  const expectedScripts=Object.freeze(['/admin-v2/core/release-marker.js','/admin-v2/core/center-renderer.js','/admin-v2/core/center-store-factory.js','/admin-v2/core/content-inventory-store.js','/admin-v2/modules/content.js','/admin-v2/core/seo-inventory-store.js','/admin-v2/modules/seo.js','/admin-v2/core/image-inventory-store.js','/admin-v2/modules/image.js','/admin-v2/core/qa-inventory-store.js','/admin-v2/modules/qa.js','/admin-v2/core/deploy-inventory-store.js','/admin-v2/modules/deploy.js','/admin-v2/core/analytics-inventory-store.js','/admin-v2/core/analytics-provider.js','/admin-v2/modules/analytics.js','/admin-v2/core/revenue-inventory-store.js','/admin-v2/modules/revenue.js','/admin-v2/core/operations-dashboard-store.js','/admin-v2/core/external-api-adapter.js','/admin-v2/core/search-console-provider.js','/admin-v2/core/adsense-provider.js','/admin-v2/core/external-retry-engine.js','/admin-v2/modules/external-connections.js','/admin-v2/modules/command.js','/admin-v2/modules/build-progress.js','/admin-v2/modules/cloudflare.js','/admin-v2/modules/seo-doctor.js','/admin-v2/modules/content-doctor.js','/admin-v2/modules/production-verification.js','/admin-v2/modules/runtime-audit.js','/admin-v2/app.js','/admin-v2/operational-actions.js','/admin-v2/production-e2e-verify.js','/admin-v2/production-deployment-probe.js','/admin-v2/production-auto-verify.js','/admin-v2/center-refresh.js']);
  function scriptLoaded(path){return [...document.scripts].some(script=>{try{return new URL(script.src,location.href).pathname===path}catch{return false}})}
  function run(){
    const moduleRows=expectedModules.map(id=>({name:`Module · ${id}`,pass:registry.has(id)}));
    const globalRows=expectedGlobals.map(name=>({name:`Core · ${name}`,pass:Boolean(window[name])}));
    const menuRows=expectedModules.map(id=>({name:`Menu · ${id}`,pass:Boolean(document.querySelector(`[data-view="${id}"]`))}));
    const scriptRows=expectedScripts.map(path=>({name:`Script · ${path}`,pass:scriptLoaded(path)}));
    const renderer=window.SavingioV2CenterRenderer?.verify?.()||{pass:false};
    const shell=window.SavingioAdminV2?.verify?.()||{pass:false};
    const progress=window.SavingioV2BuildProgressStore?.verify?.()||{pass:false,noFakeCompletion:false};
    const inventories=[['Content',window.SavingioV2ContentInventoryStore],['SEO',window.SavingioV2SeoInventoryStore],['Image',window.SavingioV2ImageInventoryStore],['QA',window.SavingioV2QaInventoryStore],['Deploy',window.SavingioV2DeployInventoryStore],['Analytics',window.SavingioV2AnalyticsInventoryStore],['Revenue',window.SavingioV2RevenueInventoryStore]].map(([name,api])=>[name,api?.verify?.()||{pass:false,count:0}]);
    const dashboard=window.SavingioV2OperationsDashboardStore?.verify?.()||{pass:false,centers:0};
    const command=window.SavingioV2CommandCenter?.verify?.()||{pass:false};
    const externalAdapter=window.SavingioV2ExternalApiAdapter?.verify?.()||{pass:false,providers:0,registered:0,noFabricatedConnection:false};
    const retryEngine=window.SavingioV2ExternalRetryEngine?.verify?.()||{pass:false,maxAttempts:0,active:0,exhausted:0,auditCount:0};
    const searchConsoleProvider=window.SavingioV2SearchConsoleProvider?.verify?.()||{pass:false,bridgeRegistered:false,propertyLock:false,noFalseAuth:false};
    const analyticsProvider=window.SavingioV2AnalyticsProvider?.verify?.()||{pass:false,bridgeRegistered:false,noFabricatedMetrics:false,inventoryCount:0};
    const adsenseProvider=window.SavingioV2AdSenseProvider?.verify?.()||{pass:false,bridgeRegistered:false,publisherLock:false,adsTxtLock:false,siteLock:false,noFabricatedStatus:false};
    const externalCenter=window.SavingioV2ExternalConnectionsCenter?.verify?.()||{pass:false};
    const productionCenter=window.SavingioV2ProductionVerificationCenter?.verify?.()||{pass:false};
    const operational=window.SavingioV2OperationalActions?.verify?.()||{pass:false,auditCount:0,lastActionPass:null};
    const e2e=window.SavingioV2ProductionE2EVerify?.run?.()||{pass:false,total:0,failed:0};
    const deploymentProbe=window.SavingioV2ProductionDeploymentProbe?.verify?.()||{pass:false,checked:false,total:0,failed:0};
    const release=window.SavingioV2ReleaseMarker||{};
    const rows=[...moduleRows,...globalRows,...menuRows,...scriptRows,{name:`Release Marker · ${expectedReleaseId}`,pass:release.id===expectedReleaseId},{name:'Release Marker module list',pass:Array.isArray(release.expectedModules)&&release.expectedModules.every(id=>registry.has(id))},{name:'Center Renderer config-driven',pass:Boolean(renderer.pass)},...inventories.map(([name,result])=>({name:`${name} Inventory integrity · ${result.count||0}건`,pass:Boolean(result.pass)})),{name:`Operations Dashboard integrity · ${dashboard.centers||0}센터`,pass:Boolean(dashboard.pass)},{name:'Command Center dashboard connection',pass:Boolean(command.pass)},{name:`External API Adapter · ${externalAdapter.registered||0}/${externalAdapter.providers||0} Provider`,pass:Boolean(externalAdapter.pass&&externalAdapter.noFabricatedConnection)},{name:`External Retry Engine · 최대 ${retryEngine.maxAttempts||0}회 · 예약 ${retryEngine.active||0} · 소진 ${retryEngine.exhausted||0}`,pass:Boolean(retryEngine.pass)},{name:`Search Console Provider · Bridge ${searchConsoleProvider.bridgeRegistered?'등록':'대기'}`,pass:Boolean(searchConsoleProvider.pass&&searchConsoleProvider.propertyLock&&searchConsoleProvider.noFalseAuth)},{name:`Analytics Provider · Bridge ${analyticsProvider.bridgeRegistered?'등록':'대기'} · Inventory ${analyticsProvider.inventoryCount||0}건`,pass:Boolean(analyticsProvider.pass&&analyticsProvider.noFabricatedMetrics)},{name:`AdSense Provider · Bridge ${adsenseProvider.bridgeRegistered?'등록':'대기'}`,pass:Boolean(adsenseProvider.pass&&adsenseProvider.publisherLock&&adsenseProvider.adsTxtLock&&adsenseProvider.siteLock&&adsenseProvider.noFabricatedStatus)},{name:'External Connections Center',pass:Boolean(externalCenter.pass)},{name:'Production Verification Center',pass:Boolean(productionCenter.pass)},{name:`Operational action bridge · 감사 ${operational.auditCount||0}건`,pass:Boolean(operational.pass)},{name:'Latest urgent-fix action E2E',pass:operational.lastActionPass===null?true:Boolean(operational.lastActionPass)},{name:`Production E2E · ${e2e.total||0}항목 / FAIL ${e2e.failed||0}`,pass:Boolean(e2e.pass)},{name:`Production asset probe · ${deploymentProbe.passed||0}/${deploymentProbe.total||0}`,pass:Boolean(deploymentProbe.pass)},{name:'Build Progress truth lock',pass:Boolean(progress.pass&&progress.noFakeCompletion)},{name:'Admin V2 Shell',pass:Boolean(shell.pass)}];
    return Object.freeze({rows,total:rows.length,passed:rows.filter(row=>row.pass).length,failed:rows.filter(row=>!row.pass).length,pass:rows.every(row=>row.pass),checkedAt:new Date().toISOString(),releaseId:release.id||'미확인',version:release.version||'미확인',e2e,deploymentProbe,operational,externalAdapter,retryEngine,searchConsoleProvider,analyticsProvider,adsenseProvider});
  }
  function render(){const result=run();const progress=window.SavingioV2BuildProgressStore?.read?.()||{};const rows=result.rows.map(row=>`<div><span>${esc(row.name)}</span><strong class="${row.pass?'pass':'fail'}">${row.pass?'PASS':'FAIL'}</strong></div>`).join('');const finalState=progress.status==='complete'&&Number(progress.percent)===100?'100% 완료':'검증 결과 미반영';return `<section class="view" data-module-root><header class="hero"><p>RUNTIME AUDIT</p><h2>Admin V2 런타임 검증 센터</h2><p>외부 Provider와 제한형 자동 재시도 엔진까지 실제 로딩 상태를 검사합니다.</p></header><div class="metrics"><article class="metric"><span>전체 항목</span><strong>${result.total}</strong></article><article class="metric"><span>PASS</span><strong>${result.passed}</strong></article><article class="metric"><span>FAIL</span><strong>${result.failed}</strong></article><article class="metric"><span>재시도 예약</span><strong>${result.retryEngine.active||0}건</strong></article><article class="metric"><span>재시도 소진</span><strong>${result.retryEngine.exhausted||0}건</strong></article><article class="metric"><span>진행 보드</span><strong>${esc(finalState)}</strong></article></div><section class="panel"><h3>실시간 검사 결과</h3><div class="connection-list">${rows}</div><div class="header-actions"><button class="button secondary" type="button" data-runtime-audit="rerun">다시 검사</button><button class="button" type="button" data-runtime-audit="apply">검사 결과 반영</button><button class="button secondary" type="button" data-route="tool-production-verification">운영 검증 센터</button><button class="button secondary" type="button" data-route="tool-external-connections">외부 연결 센터</button></div></section></section>`;}
  registry.register({id:'tool-runtime-audit',title:'런타임 검증 센터',render});
  document.addEventListener('click',event=>{const button=event.target.closest('[data-runtime-audit]');if(!button)return;event.preventDefault();if(button.dataset.runtimeAudit==='apply'){const result=run();window.SavingioV2BuildProgressStore?.applyRuntimeAudit?.(result);}window.SavingioAdminV2?.mount?.('tool-runtime-audit','replace');});
  Object.defineProperty(window,'SavingioV2RuntimeAudit',{value:Object.freeze({run}),writable:false,configurable:false});
})();