from __future__ import annotations
import html, json, re, shutil
from pathlib import Path
import argparse

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"factory/output/rebuild_pilot/site/articles"

COMMON_RELATED=[
 ("아랫집 누수 연락을 받았을 때","/articles/apartment-leak-emergency-response.html","급한 조치부터 책임 확인까지"),
 ("일배책 누수 보험 처리","/articles/daily-liability-leak-insurance.html","가입 확인·접수·서류 순서"),
 ("수도 누수 자가진단","/articles/home-water-leak-self-check.html","계량기로 옥내누수 확인"),
 ("아파트 관리비 점검","/articles/apartment-management-fee-summer.html","고지서 항목별 비교"),
 ("장기충당금 반환 확인","/articles/장기수선충당금-소유자-부담과-임차인-반환-확인-107af18f.html","소유자 부담과 임차인 정산"),
]

TOPICS=[
 dict(file="apartment-leak-emergency-response.html",title="아랫집 누수 연락을 받았을 때, 윗집이 바로 할 일",badge="누수 긴급 대응",icon="💧",intents="누수,아랫집 누수,아랫집누수,윗집 누수,윗집누수,천장 누수,물이 새요,누수 보험처리",lead="아랫집에서 물이 샌다는 연락을 받았다면 책임을 따지기 전에 물 사용을 멈추고 현장을 남겨야 합니다. 관리사무소·집주인·보험사에 알리는 순서까지 한 번에 확인하세요.",summary=[("1. 물부터 멈추기","세탁기·욕실·싱크대 사용을 멈추고 안전하면 세대 밸브를 잠급니다."),("2. 양쪽 현장 기록","윗집 설비와 아랫집 천장 피해를 시간·위치가 보이게 촬영합니다."),("3. 동시에 알리기","관리사무소, 임대인, 보험사에 사고 사실을 접수하고 담당자를 기록합니다."),("4. 원인 후 책임 판단","전용배관·공용배관·방수층 중 원인을 확인하기 전 배상을 확정하지 않습니다.")],sections=[("now","연락 직후 30분에 할 일",["진행 중인 물 사용을 모두 멈춥니다. 물과 전기가 함께 노출된 장소는 직접 만지지 않습니다.","아랫집에 젖은 위치, 처음 발견한 시간, 물이 계속 흐르는지 물어보고 사진과 영상을 요청합니다.","공동주택은 관리사무소에 공용배관 가능성까지 포함해 접수합니다. 세입자는 집주인에게 문자로도 알립니다.","보험 가입 여부가 확실하지 않아도 사고 사실을 먼저 알리고, 수리 전에 필요한 사진과 서류를 확인합니다."]),("cause","누수 원인에 따라 책임이 달라집니다",["물이 위에서 내려왔다고 해서 항상 윗집 거주자의 책임으로 바로 확정되는 것은 아닙니다.","세대 내부 급·배수관이나 설비, 공용배관, 외벽·옥상, 방수층 등 원인과 관리 주체를 조사해야 합니다.","탐지업체에는 누수 위치, 확인 방법, 원인 추정과 수리 범위를 분리한 보고서를 요청하세요."]),("repair","탐지·수리·복구 순서",["피해 확대 방지와 촬영을 먼저 하고 원인 탐지를 진행합니다.","보험사에 수리 전 승인이나 추가 촬영이 필요한지 확인합니다.","원인 부위를 수리한 뒤 충분히 건조하고, 그 다음 아랫집 천장·벽지 등 2차 피해를 복구합니다."])],faq=[("무조건 윗집이 배상해야 하나요?","아닙니다. 실제 원인과 전용·공용부분 여부, 점유자와 소유자의 관리 가능성을 확인해야 합니다."),("아랫집이 바로 도배비를 요구하면요?","피해 자료와 견적을 받고 원인 수리와 건조가 끝난 뒤 복구 범위를 정하세요."),("세입자인데 집주인이 연락되지 않아요.","문자와 통화기록으로 알린 사실을 남기고 관리사무소에 접수하세요.")],sources=[("법제처 찾기쉬운 생활법령 윗층 누수 사례","https://www.easylaw.go.kr/CSP/SolomonRetrieve.laf?sortType=READ&topMenu=serviceUl6&trialNo=1865"),("국가법령정보센터 민법 제758조","https://www.law.go.kr/법령/민법/제758조")]),
 dict(file="daily-liability-leak-insurance.html",title="일배책 누수 보험 처리, 아랫집 피해 접수 순서",badge="누수 보험",icon="🛡️",intents="일배책,일배책 누수,일상생활배상책임,누수 보험,아랫집 누수 보험처리,누수 자기부담금",lead="가족 보험에 일상생활배상책임 특약이 있는지 확인하고, 누수 원인과 피해 자료를 준비해 사고를 접수하는 순서를 정리했습니다.",summary=[("가입부터 확인","가족의 운전자·어린이·종합보험에서 일상생활배상책임 특약을 찾습니다."),("사고일을 정확히","사고를 알게 된 날짜와 장소, 피보험자와 거주자 관계를 설명합니다."),("수리 전에 촬영","원인 부위, 피해 범위, 탐지 과정과 수리 전후 사진을 남깁니다."),("보상 범위를 구분","원인 수리비와 아랫집 배상 손해가 같은 범위인지 담당자에게 확인합니다.")],sections=[("join","가입 확인 방법",["보험증권과 보험사 앱에서 일상생활배상책임, 가족일상생활배상책임 등 특약명을 확인합니다.","가족 보험을 함께 확인하되 동일한 손해를 중복 보상받을 수 있다고 단정하지 않습니다."]),("claim","사고 접수 순서",["주소, 사고일, 누수 발견 경위, 피해 세대와의 관계를 정리해 보험사에 접수합니다.","접수번호와 담당자를 기록하고 수리 전 필요한 현장조사·사진·견적 조건을 서면으로 확인합니다.","임의로 전액 합의하거나 피해 물품을 버리기 전에 담당자 안내를 확인합니다."]),("docs","준비할 자료",["누수탐지 보고서, 원인 부위 사진, 아랫집 피해 사진, 수리·복구 견적과 영수증을 모읍니다.","자기부담금, 보상 제외 사유, 사고 장소와 피보험자 범위는 계약마다 다르므로 약관과 담당자 답변을 기준으로 판단합니다."])],faq=[("원인 수리비도 전부 보상되나요?","원인 부위 수리비와 타인에게 발생한 배상 손해의 처리 범위는 계약에 따라 다릅니다."),("가족 보험이 여러 개면 여러 번 받나요?","같은 손해를 실제 손해액을 넘어서 중복 보상받는다고 단정할 수 없습니다."),("먼저 합의해도 되나요?","지급이나 합의 전에 보험사 담당자와 필요한 절차를 확인하는 편이 안전합니다.")],sources=[("금융감독원 금융소비자정보포털 파인","https://fine.fss.or.kr/")]),
 dict(file="home-water-leak-self-check.html",title="수도 누수 자가진단, 계량기로 우리 집 누수 확인하는 방법",badge="누수 원인 확인",icon="🚰",intents="수도 누수,누수 자가진단,수도계량기 누수,옥내누수,수도요금 누수,물을 안 쓰는데 계량기",lead="모든 수도 사용을 멈춘 뒤 계량기 별표나 지침이 움직이는지 확인해 옥내누수 가능성을 점검하는 방법입니다.",summary=[("모든 물 사용 중지","수도꼭지·세탁기·정수기·변기 물 채움까지 멈춘 상태를 만듭니다."),("계량기 움직임 확인","물을 쓰지 않는데 별 모양이나 지침이 계속 움직이는지 봅니다."),("시간을 두고 재확인","계량기 숫자를 촬영하고 10~20분 뒤 같은 각도로 다시 확인합니다."),("움직이면 전문가 점검","임의 철거보다 관리사무소·수도사업소·전문업체에 먼저 문의합니다.")],sections=[("check","계량기 확인 순서",["집 안의 모든 수도 사용을 중지하고 세탁기·식기세척기·정수기·변기가 작동 중인지 확인합니다.","계량기함을 열어 현재 숫자와 별표 또는 미세 지침을 사진으로 남깁니다.","아무도 물을 쓰지 않는 상태를 유지한 뒤 다시 촬영합니다. 계속 움직이거나 숫자가 증가하면 옥내누수를 의심할 수 있습니다."]),("places","먼저 볼 장소",["변기 물탱크 내부, 싱크대와 세면대 하부, 세탁기 급수호스, 보일러 주변, 벽·천장의 젖은 자국을 확인합니다.","공동주택은 공용배관 가능성이 있으므로 관리사무소에 같은 동·라인의 이상 여부도 문의합니다."]),("bill","요금이 갑자기 늘었다면",["이번 달만 보지 말고 전년 같은 달 사용량과 비교합니다.","옥내누수 감면 제도와 제출서류는 지역 수도사업자마다 다를 수 있으므로 수리 전후 사진과 영수증을 보관하세요."])],faq=[("계량기가 움직이면 무조건 누수인가요?","정수기나 변기 급수처럼 눈에 잘 띄지 않는 사용이 없는지 먼저 확인한 뒤 재점검해야 합니다."),("계량기 이후 누수 요금도 부과되나요?","일반적으로 계량기를 통과한 사용량에 요금이 부과될 수 있으며 지역별 감면 기준을 확인해야 합니다."),("직접 벽을 뜯어도 되나요?","원인 위치가 불확실하면 임의 철거보다 전문가 점검을 먼저 받는 편이 안전합니다.")],sources=[("안산시 상하수도사업소 옥내누수 확인방법","https://www.ansan.go.kr/water/common/cntnts/selectContents.do?cntnts_id=C0001899")],calc=("전기요금 계산기로 관리비 사용량 함께 점검","/calculators/electricity.html")),
 dict(file="apartment-management-fee-summer.html",title="아파트 관리비 줄이는 방법과 항목별 점검표",badge="아파트 관리비",icon="🏢",intents="아파트 관리비,관리비 절약,관리비 많이 나옴,공용관리비,장기충당금,아파트 고지서",lead="관리비 총액만 보지 말고 세대사용료·공용관리비·장기수선충당금을 나눠 전년 같은 달과 비교하는 방법입니다.",summary=[("세대·공용 분리","내가 사용한 요금과 단지 전체가 함께 부담하는 비용을 나눕니다."),("전년 동월 비교","계절 영향을 줄이려면 전월보다 지난해 같은 달과 비교합니다."),("단가·사용량 구분","사용량이 늘었는지 단가나 정산 방식이 바뀌었는지 확인합니다."),("이상 항목 문의","관리사무소에 산정 근거, 검침값과 부과 기준을 요청합니다.")],sections=[("read","고지서를 세 그룹으로 나누세요",["전기·수도·가스·난방처럼 세대가 직접 사용한 요금, 청소·경비·승강기·공용전기 같은 공용관리비, 장기수선충당금·보험료 같은 고정성 항목으로 나눕니다.","총액만 비교하면 원인을 찾기 어렵습니다. 항목별 금액과 사용량을 함께 보세요."]),("compare","비교 순서",["전년 같은 달, 비슷한 면적과 난방방식의 단지, 세대원 수 변화를 함께 봅니다.","K-apt 공개자료와 고지서를 비교하되 단지 연식·시설·경비 방식이 다른 단지와 단순 비교하지 않습니다."]),("reserve","세입자는 장기수선충당금을 따로 확인하세요",["관리비와 함께 납부했더라도 최종 부담 주체와 퇴거 정산은 별도로 확인해야 합니다.","납부확인서, 임대차계약서와 계좌내역을 보관하고 관리사무소에 기간별 납부액을 요청하세요."])],faq=[("관리비가 많이 나오면 어디에 문의하나요?","고지서를 발행한 관리사무소에 항목별 산정 근거와 검침값을 문의하세요."),("다른 아파트보다 비싸면 문제인가요?","단지 규모·연식·난방·경비 방식이 달라 비슷한 조건끼리 항목별로 비교해야 합니다."),("공용전기료도 줄일 수 있나요?","관리사무소와 입주자대표회의를 통해 운영시간과 설비 효율을 점검할 수 있습니다.")],sources=[("공동주택관리정보시스템 K-apt","https://www.k-apt.go.kr/")],calc=("전기 사용량으로 예상요금 계산","/calculators/electricity.html")),
 dict(file="장기수선충당금-소유자-부담과-임차인-반환-확인-107af18f.html",title="장기수선충당금은 누가 내고, 세입자는 어떻게 돌려받나요?",badge="장기충당금",icon="🏠",intents="장기수선충당금,장기충당금,장충금,수선충당금,세입자 장기충당금,임차인 반환,장기수선충당금 돌려받기",lead="장기수선충당금의 법정 부담 주체와 세입자가 대신 납부한 금액을 이사할 때 확인·정산하는 순서를 정리했습니다.",summary=[("원칙은 소유자 부담","공동주택관리법은 해당 주택 소유자로부터 징수해 적립하도록 규정합니다."),("세입자 선납 여부 확인","관리비 고지서에서 매월 납부한 장기수선충당금 기간과 금액을 확인합니다."),("관리사무소 확인서 발급","입주일부터 퇴거일까지의 납부확인서를 요청합니다."),("임대인과 정산 기록","확인서와 계약서를 근거로 반환 금액·지급일을 문자나 문서로 남깁니다.")],sections=[("rule","장기수선충당금 부담 원칙",["공동주택관리법 제30조는 주요 시설 교체·보수에 필요한 장기수선충당금을 해당 주택의 소유자로부터 징수해 적립하도록 규정합니다.","관리비 고지서에 포함되어 실제로는 세입자가 먼저 납부한 경우가 있으므로 최종 부담과 정산을 구분해야 합니다."]),("return","세입자 반환 확인 순서",["관리비 고지서와 계좌이체 내역에서 납부 기간을 확인합니다.","관리사무소에 입주일부터 퇴거일까지 장기수선충당금 납부확인서를 요청합니다.","임대차계약서의 특약과 정산 내역을 확인하고 임대인에게 확인서와 반환 요청 금액을 전달합니다.","열쇠 인도와 보증금 정산 전에 지급 시점과 방법을 기록합니다."]),("calc","금액이 다를 때 확인할 것",["중간에 요율이 변경됐는지, 공실 기간이나 미납 기간이 있는지, 입주·퇴거일 기준이 정확한지 확인합니다.","장기수선충당금과 수선유지비 등 이름이 비슷한 다른 관리비 항목을 섞지 않습니다."])],faq=[("장기충당금이라고 검색해도 같은 돈인가요?","일상적으로 장기충당금·장충금이라고 줄여 부르기도 하지만 고지서의 정확한 항목명을 확인하세요."),("퇴거 뒤에도 요청할 수 있나요?","계약과 납부자료를 확인해 임대인과 정산할 수 있으나 분쟁 가능성을 줄이려면 퇴거 정산 때 확인하는 편이 좋습니다."),("관리사무소가 직접 돌려주나요?","관리사무소는 납부확인서를 발급하고 실제 반환은 임대인과 정산하는 구조인지 확인해야 합니다.")],sources=[("국가법령정보센터 공동주택관리법 제30조","https://www.law.go.kr/lsLinkCommonInfo.do?lsJoLnkSeq=1011745203"),("국가법령정보센터 공동주택관리법 시행령 제31조","https://www.law.go.kr/lsLinkCommonInfo.do?chrClsCd=010202&lspttninfSeq=132107")])]

for _topic in TOPICS:
 if _topic['file']=='daily-liability-leak-insurance.html' and '누수 보험처리' not in _topic['intents'].split(','):
  _topic['intents']+=',누수 보험처리'

def cards(items): return ''.join(f'<div class="rb-card"><strong>{html.escape(a)}</strong><span>{html.escape(b)}</span></div>' for a,b in items)
def related(current): return ''.join(f'<a href="{u}"'+(' aria-current="page"' if u.endswith(current) else '')+f'><strong>{html.escape(t)}</strong><span>{html.escape(d)}</span></a>' for t,u,d in COMMON_RELATED)
def render(t):
 toc=''.join(f'<a href="#{i}">{html.escape(h)}</a>' for i,h,_ in t['sections'])+'<a href="#faq">FAQ</a><a href="#related">관련 글</a>'
 body=''.join(f'<section class="rb-section" id="{i}"><h2>{html.escape(h)}</h2>'+''.join(f'<p>{html.escape(p)}</p>' for p in ps)+'</section>' for i,h,ps in t['sections'])
 faq=''.join(f'<details><summary>{html.escape(q)}</summary><p>{html.escape(a)}</p></details>' for q,a in t['faq'])
 src=''.join(f'<li><a href="{u}" rel="noopener" target="_blank">{html.escape(n)}</a></li>' for n,u in t['sources'])
 calc=''
 if t.get('calc'): calc=f'<section class="rb-section rb-calc"><h2>관련 계산기</h2><p>{html.escape(t["calc"][0])}</p><a class="rb-button" href="{t["calc"][1]}">계산기 열기 →</a></section>'
 desc=t['lead']; title=t['title']; url='https://savingio.com/articles/'+t['file']
 return f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | 세이빙이오</title><meta name="description" content="{html.escape(desc)}"><meta name="savingio:search-intents" content="{html.escape(t['intents'])}"><link rel="canonical" href="{url}"><link rel="stylesheet" href="/css/article-rebuild-v1.css?v=1"><link rel="stylesheet" href="/css/savingio-brain-navigation.css?v=12"><link rel="stylesheet" href="/css/calculator-drawer.css?v=18"></head><body data-rebuild="v1"><header class="rb-header"><nav class="rb-nav"><a class="rb-logo" href="/">세이빙이오(Savingio)</a><div class="rb-links"><a href="/articles/">정보센터</a><a href="/calculators/">계산기</a><a href="/about.html">소개</a></div></nav></header><section class="rb-hero"><div class="rb-hero-in"><span class="rb-badge">{html.escape(t['badge'])}</span><h1>{html.escape(title)}</h1><p class="rb-lead">{html.escape(desc)}</p><p class="rb-meta">최종 업데이트 2026년 7월 17일 · 세이빙이오 편집팀</p></div></section><figure class="rb-thumb" data-factory-hero="true"><div class="rb-thumb-icon">{t['icon']}</div><figcaption><span>Savingio · {html.escape(t['badge'])}</span><strong>{html.escape(title)}</strong><small>급한 순서부터 차례로 확인하세요</small></figcaption></figure><main class="rb-main"><nav class="rb-toc" aria-label="목차">{toc}</nav><article><section class="rb-section"><h2>3초 요약</h2><div class="rb-grid">{cards(t['summary'])}</div></section>{body}<section class="rb-section rb-faq" id="faq"><h2>자주 묻는 질문</h2>{faq}</section>{calc}<section class="rb-section" id="related"><h2>다음 문제까지 이어서 해결</h2><div class="rb-related">{related(t['file'])}</div></section><section class="rb-section rb-sources"><h2>공식 근거</h2><ul>{src}</ul><p>실제 책임·보상·정산은 원인, 계약, 약관과 최신 기준에 따라 달라질 수 있으므로 공식 안내를 최종 확인하세요.</p></section></article></main><footer class="rb-footer"><div class="rb-footer-in"><strong>세이빙이오(Savingio)</strong> · <a href="/editorial-policy.html">콘텐츠 운영 원칙</a> · <a href="/contact.html">문의</a></div></footer><script src="/data/savingio-brain-data.js?v=12"></script><script src="/js/savingio-brain-navigation.js?v=12"></script><script src="/js/calculator-drawer.js?v=18"></script></body></html>'''

def main(apply=False):
 if OUT.parent.exists(): shutil.rmtree(OUT.parent)
 OUT.mkdir(parents=True)
 report=[]
 for t in TOPICS:
  text=render(t); (OUT/t['file']).write_text(text,encoding='utf-8')
  if apply:
   (ROOT/'articles'/t['file']).write_text(text,encoding='utf-8')
  report.append(dict(file=t['file'],h1=len(re.findall(r'<h1\b',text)),hero=text.count('data-factory-hero="true"'),brain=text.count('savingio-brain-navigation.js?v=12'),calculator=('rb-calc' in text),related=text.count('class="rb-related"')))
 (OUT.parent/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=='__main__':
 parser=argparse.ArgumentParser(); parser.add_argument('--apply',action='store_true'); args=parser.parse_args(); main(args.apply)
