const enc=new TextEncoder();
async function hash(v){return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
async function equal(a,b){const[x,y]=await Promise.all([hash(a),hash(b)]);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'private, no-store','x-robots-tag':'noindex, nofollow, noarchive'}})}
async function auth(req,env){const h=req.headers.get('authorization')||'';if(!h.startsWith('Basic ')||!env.SAVINGIO_HQ_USER||!env.SAVINGIO_HQ_PASSWORD)return false;let s='';try{s=atob(h.slice(6))}catch{return false}const p=s.indexOf(':');if(p<0)return false;return (await equal(s.slice(0,p),env.SAVINGIO_HQ_USER))&&(await equal(s.slice(p+1),env.SAVINGIO_HQ_PASSWORD))}
function cfg(env){return{repo:env.SAVINGIO_GITHUB_REPO||'yusun7749-art/savingio',branch:env.SAVINGIO_GITHUB_BRANCH||'main',token:env.SAVINGIO_GITHUB_TOKEN}}
async function gh(env,path,opt={}){const c=cfg(env);if(!c.token)throw new Error('SAVINGIO_GITHUB_TOKEN 미설정');const r=await fetch(`https://api.github.com/repos/${c.repo}/${path}`,{...opt,headers:{accept:'application/vnd.github+json',authorization:`Bearer ${c.token}`,'user-agent':'Savingio-HQ','x-github-api-version':'2022-11-28',...(opt.headers||{})}});const t=await r.text();let data={};try{data=t?JSON.parse(t):{}}catch{data={message:t}}if(!r.ok)throw new Error(data.message||`GitHub ${r.status}`);return data}
function safePath(path){if(typeof path!=='string'||!/^articles\/[a-z0-9][a-z0-9-]*\.html$/.test(path))throw new Error('허용되지 않은 글 경로');return path}
function decode64(v){return new TextDecoder().decode(Uint8Array.from(atob((v||'').replace(/\n/g,'')),c=>c.charCodeAt(0)))}
function encode64(v){let s='';for(const b of new TextEncoder().encode(v))s+=String.fromCharCode(b);return btoa(s)}
async function readFile(env,path){const c=cfg(env);const d=await gh(env,`contents/${path}?ref=${encodeURIComponent(c.branch)}`);return{path,sha:d.sha,html:decode64(d.content)}}
async function putFile(env,path,content,sha,message){const c=cfg(env);return gh(env,`contents/${path}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({message,content:encode64(content),sha,branch:c.branch})})}
async function createFile(env,path,content,message){const c=cfg(env);return gh(env,`contents/${path}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({message,content:encode64(content),branch:c.branch})})}
async function deleteFile(env,path,sha,message){const c=cfg(env);return gh(env,`contents/${path}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({message,sha,branch:c.branch})})}
async function removeFromSitemap(env,articlePath){const f=await readFile(env,'sitemap.xml');const url=`https://savingio.com/${articlePath}`;const escaped=url.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const next=f.html.replace(new RegExp(`\\s*<url><loc>${escaped}<\\/loc><\\/url>`,'g'),'');if(next!==f.html)await putFile(env,'sitemap.xml',next,f.sha,`HQ remove ${articlePath} from sitemap`)}
function hideHtml(html){let out=html;if(/<meta\s+name=["']robots["']/i.test(out))out=out.replace(/<meta\s+name=["']robots["'][^>]*>/i,'<meta name="robots" content="noindex,nofollow,noarchive">');else out=out.replace(/<head([^>]*)>/i,'<head$1>\n  <meta name="robots" content="noindex,nofollow,noarchive">');if(!/data-savingio-hidden=/i.test(out))out=out.replace(/<html([^>]*)>/i,'<html$1 data-savingio-hidden="true">');return out}
export async function onRequest(context){if(!(await auth(context.request,context.env)))return json({ok:false,error:'인증 필요'},401);try{const u=new URL(context.request.url);if(context.request.method==='GET'){const path=safePath(u.searchParams.get('path')||'');const f=await readFile(context.env,path);return json({ok:true,...f})}if(context.request.method!=='POST')return json({ok:false,error:'지원하지 않는 요청'},405);const body=await context.request.json();const path=safePath(body.path);if(body.action==='edit'){if(typeof body.html!=='string'||body.html.length<100)throw new Error('HTML 내용이 너무 짧습니다');const f=await readFile(context.env,path);const r=await putFile(context.env,path,body.html,f.sha,`HQ edit ${path}`);return json({ok:true,action:'edit',commit:r.commit?.sha})}if(body.action==='hide'){const f=await readFile(context.env,path);const r=await putFile(context.env,path,hideHtml(f.html),f.sha,`HQ hide ${path}`);await removeFromSitemap(context.env,path);return json({ok:true,action:'hide',commit:r.commit?.sha})}if(body.action==='delete'){const f=await readFile(context.env,path);const stamp=new Date().toISOString().replace(/[:.]/g,'-');const trash=`_trash/${stamp}-${path.replace('/','-')}`;await createFile(context.env,trash,f.html,`HQ backup before delete ${path}`);const r=await deleteFile(context.env,path,f.sha,`HQ delete ${path}`);await removeFromSitemap(context.env,path);return json({ok:true,action:'delete',trash,commit:r.commit?.sha})}throw new Error('알 수 없는 작업');}catch(e){return json({ok:false,error:e.message||'처리 실패'},400)}}