(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=v=>JSON.parse(JSON.stringify(v));
  let range='7d', source='all', level='all', project='all', query='', view='table', autoRefresh=true;
  const safeList=api=>{try{const v=api?.list?.();return Array.isArray(v)?v:[]}catch{return[]}};
  const now=()=>new Date().toISOString();
  const time=v=>{const n=Date.parse(v||'');return Number.isFinite(n)?n:0};
  const levelOf=(state='')=>/fail|error|blocked|unhealthy|rejected|critical/i.test(state)?'error':/warn|pending|queued|review|waiting|paused/i.test(state)?'warn':/success|done|healthy|deployed|approved|resolved/i.test(state)?'success':'info';
  function row(input={}){return {id:String(input.id||`LOG-${Math.random().toString(36).slice(2)}`),source:String(input.source||'system'),level:String(input.level||levelOf(input.state)),projectId:String(input.projectId||''),title:String(input.title||'활동 기록'),message:String(input.message||''),state:String(input.state||''),createdAt:input.createdAt||now(),targetId:String(input.targetId||''),raw:input.raw||input};}
  function collect(){
    const out=[];
    safeList(window.SavingioProject).forEach(x=>out.push(row({id:`project-${x.id}`,source:'project',projectId:x.id,title:x.title||x.id,message:x.description||'프로젝트 상태 변경',state:x.status,createdAt:x.updatedAt||x.createdAt,raw:x})));
    safeList(window.SavingioWorkflow).forEach(w=>{(w.logs||[]).forEach(l=>out.push(row({id:l.id,source:'workflow',projectId:w.projectId,title:l.title,message:l.message,state:l.level,level:l.level==='error'?'error':l.level==='warn'?'warn':l.level==='success'?'success':'info',createdAt:l.createdAt,targetId:l.targetId,raw:l})));(w.approvals||[]).forEach(a=>out.push(row({id:a.id,source:'approval',projectId:w.projectId,title:`${a.stageName} ${a.action}`,message:a.note,state:a.action,createdAt:a.createdAt,raw:a})));});
    safeList(window.SavingioAutomation).forEach(x=>out.push(row({id:x.id,source:'automation',projectId:x.projectId,title:x.title,message:x.error||`${x.repository||''} ${x.branch||''}`.trim(),state:x.status,createdAt:x.updatedAt||x.createdAt,raw:x})));
    safeList(window.SavingioGitHubStatus).forEach(x=>out.push(row({id:`github-${x.jobId}`,source:'github',projectId:x.projectId,title:x.commitSha?`Commit ${x.commitSha.slice(0,8)}`:'GitHub 상태',message:x.message,state:x.state,createdAt:x.checkedAt,raw:x})));
    safeList(window.SavingioCloudflareDeploy).forEach(x=>out.push(row({id:x.id,source:'cloudflare',projectId:x.projectId,title:`${x.projectName} 배포`,message:x.error||x.deploymentUrl||x.productionUrl,state:x.state,createdAt:x.updatedAt||x.createdAt,raw:x})));
    safeList(window.SavingioUrlHealth).forEach(x=>out.push(row({id:x.id,source:'url',projectId:x.projectId,title:x.url||'URL 검사',message:x.error||`HTTP ${x.httpStatus||'-'} · ${x.responseTimeMs||0}ms`,state:x.state,createdAt:x.checkedAt||x.updatedAt||x.createdAt,raw:x})));
    safeList(window.SavingioRetry).forEach(x=>out.push(row({id:x.id,source:'retry',projectId:x.projectId,title:`${x.targetType} 재시도`,message:x.error||x.reason,state:x.status,createdAt:x.updatedAt||x.createdAt,raw:x})));
    safeList(window.SavingioOperationsErrorCenter).forEach(x=>out.push(row({id:x.id,source:'error',projectId:x.projectId,title:x.title,message:x.message,state:x.status,level:x.severity==='critical'||x.severity==='high'?'error':x.severity==='medium'?'warn':'info',createdAt:x.lastSeenAt||x.firstSeenAt,raw:x})));
    const qa=window.SavingioOperationsHQ?.qa?.();(qa?.items||[]).forEach(x=>out.push(row({id:`qa-${x.id}`,source:'qa',title:x.title,message:`오류 ${x.errors||0} · 주의 ${x.warnings||0}`,state:x.status,createdAt:qa.completedAt||now(),raw:x})));
    return out.filter(x=>time(x.createdAt)).sort((a,b)=>time(b.createdAt)-time(a.createdAt)).slice(0,1000);
  }
  function filtered(rows){const cutoff=range==='1d'?Date.now()-864e5:range==='7d'?Date.now()-6048e5:range==='30d'?Date.now()-2592e6:0;const term=query.trim().toLowerCase();return rows.filter(x=>(!cutoff||time(x.createdAt)>=cutoff)&&(source==='all'||x.source===source)&&(level==='all'||x.level===level)&&(project==='all'||x.projectId===project)&&(!term||[x.title,x.message,x.projectId,x.source,x.state].some(v=>String(v||'').toLowerCase().includes(term))));}
  function download(name,text,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
  function exportCsv(rows){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;download(`savingio-logs-${Date.now()}.csv`,['time,source,level,project,title,message,state',...rows.map(x=>[x.createdAt,x.source,x.level,x.projectId,x.title,x.message,x.state].map(q).join(','))].join('\n'),'text/csv;charset=utf-8');}
  function render(){const host=$('.operations-hq');if(!host)return;let panel=$('#operationsLogViewer');if(!panel){panel=document.createElement('article');panel.id='operationsLogViewer';panel.className='ops-panel ops-wide ops-log-viewer';host.appendChild(panel);}const all=collect(), rows=filtered(all), projects=[...new Set(all.map(x=>x.projectId).filter(Boolean))], sources=[...new Set(all.map(x=>x.source))];panel.innerHTML=`<header><div><h4>통합 로그 뷰어</h4><small>Project부터 URL 검증까지 운영 로그를 한곳에서 검색합니다.</small></div><div><button class="btn ghost small" data-log-action="refresh">새로고침</button><button class="btn ghost small" data-log-action="csv">CSV</button><button class="btn ghost small" data-log-action="json">JSON</button></div></header><div class="ops-log-summary"><article><small>전체</small><strong>${all.length}</strong></article><article><small>검색 결과</small><strong>${rows.length}</strong></article><article><small>오류</small><strong>${rows.filter(x=>x.level==='error').length}</strong></article><article><small>경고</small><strong>${rows.filter(x=>x.level==='warn').length}</strong></article></div><div class="ops-log-toolbar"><input type="search" data-log-search value="${esc(query)}" placeholder="프로젝트·메시지·상태 검색"><select data-log-range>${[['1d','오늘'],['7d','7일'],['30d','30일'],['all','전체']].map(([v,l])=>`<option value="${v}" ${range===v?'selected':''}>${l}</option>`).join('')}</select><select data-log-source><option value="all">전체 출처</option>${sources.map(v=>`<option value="${esc(v)}" ${source===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select data-log-level>${[['all','전체 중요도'],['error','오류'],['warn','경고'],['success','성공'],['info','정보']].map(([v,l])=>`<option value="${v}" ${level===v?'selected':''}>${l}</option>`).join('')}</select><select data-log-project><option value="all">전체 프로젝트</option>${projects.map(v=>`<option value="${esc(v)}" ${project===v?'selected':''}>${esc(v)}</option>`).join('')}</select><button class="chip ${view==='table'?'active':''}" data-log-view="table">목록</button><button class="chip ${view==='json'?'active':''}" data-log-view="json">JSON</button><label><input type="checkbox" data-log-auto ${autoRefresh?'checked':''}> 자동</label></div>${view==='json'?`<pre class="ops-log-json">${esc(JSON.stringify(rows,null,2))}</pre>`:`<div class="ops-log-list">${rows.length?rows.map(x=>`<article class="ops-log-row ${x.level}"><time>${new Date(x.createdAt).toLocaleString('ko-KR')}</time><span class="ops-log-source">${esc(x.source)}</span><div><strong>${esc(x.title)}</strong><small>${x.projectId?`${esc(x.projectId)} · `:''}${esc(x.state)}</small><p>${esc(x.message)}</p></div><em>${x.level}</em></article>`).join(''):'<p class="ops-empty">조건에 맞는 로그가 없습니다.</p>'}</div>`}`;bind(panel,rows);window.dispatchEvent(new CustomEvent('savingio:operations-log-rendered',{detail:{total:all.length,visible:rows.length}}));}
  function bind(panel,rows){$('[data-log-action="refresh"]',panel)?.addEventListener('click',render);$('[data-log-action="csv"]',panel)?.addEventListener('click',()=>exportCsv(rows));$('[data-log-action="json"]',panel)?.addEventListener('click',()=>download(`savingio-logs-${Date.now()}.json`,JSON.stringify(rows,null,2),'application/json'));$('[data-log-search]',panel)?.addEventListener('input',e=>{query=e.target.value;render();requestAnimationFrame(()=>{$('[data-log-search]')?.focus();});});$('[data-log-range]',panel)?.addEventListener('change',e=>{range=e.target.value;render();});$('[data-log-source]',panel)?.addEventListener('change',e=>{source=e.target.value;render();});$('[data-log-level]',panel)?.addEventListener('change',e=>{level=e.target.value;render();});$('[data-log-project]',panel)?.addEventListener('change',e=>{project=e.target.value;render();});$$('[data-log-view]',panel).forEach(b=>b.addEventListener('click',()=>{view=b.dataset.logView;render();}));$('[data-log-auto]',panel)?.addEventListener('change',e=>{autoRefresh=e.target.checked;});}
  function boot(){if(!$('link[data-log-viewer-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/admin/os/log-viewer.css';l.dataset.logViewerCss='true';document.head.appendChild(l);}const events=['savingio:operations-hq-rendered','savingio:projects-changed','savingio:workflows-changed','savingio:automation-jobs-changed','savingio:github-status-changed','savingio:cloudflare-deployments-changed','savingio:url-health-changed','savingio:retry-records-changed','savingio:operations-errors-changed','savingio:approval-center-changed','savingio:operations-hq-qa-completed'];events.forEach(name=>window.addEventListener(name,()=>{if(autoRefresh&&$('.operations-hq'))requestAnimationFrame(render);}));window.SavingioLogViewer=Object.freeze({collect:()=>clone(collect()),render,exportCsv:()=>exportCsv(filtered(collect()))});if($('.operations-hq'))render();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();